/* ============================================================
   fps.js
   FPS MODE — "LOBBY BREACH" (a real Wolfenstein-3D-style raycaster,
   covering all 10 floors of Indigo Tower)

   Same DDA raycasting core as the original Floor-1-only proof of
   concept: a 2D grid map rendered as per-column vertical wall strips
   whose height and shading come from fisheye-corrected distance and
   which wall axis was hit. Built on top of a follow-up revision that
   added:
     - wall strips are texture-sampled (a tileable panel texture,
       multiply-tinted a different color per floor; the amber hazard-
       stripe texture for decorative border walls is shared, untinted)
       instead of flat fills
     - the floor is real per-pixel floor-casting with a tiled texture,
       checkerboarded and multiply-tinted per floor, instead of a
       flat fill
     - badge pickups are billboarded using the existing Story Mode
       trophy tile (platform-tiles.png) instead of a drawn circle
     - the guard is billboarded using the existing Story Mode guard
       walk-cycle sprite (dave-guard.png) instead of a flat rectangle
     - a first-person weapon view (a stun pistol in hand, 2-frame
       idle/fire sprite generated by tools/gen_fps_assets.py) is drawn
       screen-space at the bottom of the canvas, Wolfenstein-3D style
     - all 10 floors are playable in sequence: clearing one (all
       badges + the elevator alcove) advances to the next; guard
       count/speed steps up on floors 6-10, matching Story Mode's own
       "tougher back half" precedent

   This revision adds, per a follow-up request:
     - mouse-look: once the canvas is clicked (Pointer Lock API),
       the mouse steers (movementX rotates the view) while the
       keyboard still moves — Up/Down walk, Left/Right become strafe
       instead of turn while locked (Esc releases the lock and falls
       back to keyboard-only turning)
     - every floor is now a real multi-room layout (six rooms, 3x2,
       connected by a spanning-tree of doors plus one extra loop-
       variety connection) instead of the old two-room entrance-hall/
       lobby split, with real Wolfenstein-3D-style doors: they slide
       open on proximity and auto-close behind the player, rendered
       with their own texture (tools/gen_fps_assets.py's fps-door.png)
       and gating both the raycaster and collision the same way a
       wall does until open
     - a hacking-terminal side-quest inside Floor 1's starting room:
       walk up to the terminal billboard (fps-terminal.png) and press
       E to open a small multiple-choice mini-puzzle; the correct
       answer grants a bonus stun charge, no penalty for a wrong guess

   Map units: the player position (posX, posY) and the grid share one
   coordinate space (cell (c, r) occupies [c, c+1) x [r, r+1)).

   Reuses window.CG (game.js's shared-services object) the same way
   story.js does, and follows the same window.Story-style module
   pattern: window.Fps = (function () { ... return {...}; })();

   Depends on: ui.js (UI.showScreen), window.CG (set up by game.js's
   init()), window.SPRITES (sprites.js — reused for the trophy/guard
   art). Does NOT depend on guards.js's SecurityGuard (its movement is
   one-axis-only, built for Story Mode's side view) — this file
   defines its own lightweight 2D FpsGuard instead.
   ============================================================ */

window.Fps = (function () {
  "use strict";

  /* ---------------- Art assets (this mode's own, plus reused sprites) --- */
  const IMG_WALL_PANEL = loadImg("img/fps-wall-panel.png");
  const IMG_WALL_HAZARD = loadImg("img/fps-wall-hazard.png");
  const IMG_FLOOR_TILE = loadImg("img/fps-floor-tile.png");
  const IMG_GUN_HAND = loadImg("img/fps-gun-hand.png");
  const IMG_DOOR = loadImg("img/fps-door.png");
  const IMG_TERMINAL = loadImg("img/fps-terminal.png");
  const FLOOR_TEX_SIZE = 32; // img/fps-floor-tile.png's native size
  const GUN_FRAME_W = 256, GUN_FRAME_H = 288; // img/fps-gun-hand.png, 2 frames side by side
  const TROPHY_SRC = { x: 80, y: 0, w: 40, h: 40 }; // platform-tiles.png's trophy column

  /* ---------------- Per-floor theming ---------------- */
  const FLOOR_THEMES = [
    { name: "Main Lobby & Badge Security", tint: "#4F46E5" },
    { name: "Human Resources & Employee Records", tint: "#0EA5E9" },
    { name: "Finance & Accounts Payable", tint: "#22C55E" },
    { name: "IT Helpdesk & Support", tint: "#F97316" },
    { name: "Legal & Compliance", tint: "#8B5CF6" },
    { name: "Network Operations Center (NOC)", tint: "#EF4444" },
    { name: "Executive Suite", tint: "#EAB308" },
    { name: "Cloud & R&D Lab", tint: "#38BDF8" },
    { name: "Data Center Corridor", tint: "#DC2626" },
    { name: "Secure Server Room", tint: "#10B981" },
  ];
  const TOTAL_FLOORS = FLOOR_THEMES.length;

  /* ---------------- Multi-room layout geometry ---------------- */
  // Every floor is a 3x2 grid of rooms (six total), connected by doors
  // along a spanning-tree "snake" path plus one extra edge for loop
  // variety. Cell values: 0 = floor, 1 = wall, 2 = decorative hazard-
  // striped wall (still solid, purely cosmetic), 3 = door.
  const ROOM_COLS = 3;
  const ROOM_ROWS = 2;
  const WALL = 1;
  const LOCKED_DOOR = 4; // a door cell that stays solid (see isWall's default) until this floor's keycard is collected
  // (col, row) order the spanning tree connects rooms in.
  const ROOM_PATH = [[0, 0], [1, 0], [2, 0], [2, 1], [1, 1], [0, 1]];

  /* ---------------- Level archetypes ----------------
     The six-room skeleton above is shared, but the FEEL of a floor is
     driven by its archetype: how big the rooms are, what's inside them,
     and what kind of enemy holds them. Three archetypes cover the
     campaign, so the 10-floor run has a real shape instead of ten
     variations on one room:

       MAINTENANCE TUNNELS (floors 1-3) — small rooms broken up by
         interior pillars into claustrophobic corridors. Guards sit in
         tight patrols around door chokepoints with a short sight range
         but a wide cone and a big point-blank radius, so they read as
         "popping out from a corner" rather than being spotted across a
         hall. Close-range reaction, no space to back off.

       DATACENTER (floors 4-7) — wide-open arenas with server racks
         scattered as hard cover, plus SNIPERS: stationary enemies that
         paint a laser sight on the player, hold the lock for a beat,
         then fire for heavy damage. The rack cover is the answer —
         breaking line of sight cancels a lock in progress, which turns
         these floors into cover-shooter rooms.

       ROOFTOP EXTRACTION (floors 8-10) — one big survival arena. The
         exit stays sealed until an extraction timer runs out while waves
         of enemies spawn in on a cadence. Explosive barrels are placed
         around the arena as a crowd-control tool: shoot one and it takes
         out everything near it (including the player, if they're too
         close). */
  const ARCH_TUNNELS = "tunnels";
  const ARCH_DATACENTER = "datacenter";
  const ARCH_ROOFTOP = "rooftop";

  function archetypeFor(floorIndex) {
    if (floorIndex <= 2) return ARCH_TUNNELS;
    if (floorIndex <= 6) return ARCH_DATACENTER;
    return ARCH_ROOFTOP;
  }

  const ARCHETYPE_LABEL = {
    [ARCH_TUNNELS]: "Maintenance Tunnels",
    [ARCH_DATACENTER]: "Datacenter",
    [ARCH_ROOFTOP]: "Rooftop Extraction",
  };

  // Rooftop extraction tuning.
  const HOLDOUT_BASE_SECONDS = 45;      // floor 8; later rooftops add more
  const HOLDOUT_PER_FLOOR_SECONDS = 12;
  const WAVE_INTERVAL = 9;              // seconds between wave spawns
  const WAVE_ENEMY_BASE = 2;            // enemies in wave 1
  const BARREL_RADIUS = 2.4;            // blast radius, grid units
  const BARREL_PLAYER_DAMAGE = 30;

  // Sniper tuning (datacenter floors).
  const SNIPER_LOCK_TIME = 1.5;         // seconds of laser-sight lock before it fires
  const SNIPER_DAMAGE = 20;
  const SNIPER_COOLDOWN = 2.2;
  const SNIPER_RANGE = 14;

  function setBlock(grid, r0, c0, r1, c1, val) {
    for (let r = r0; r <= r1; r++) {
      for (let c = c0; c <= c1; c++) grid[r][c] = val;
    }
  }

  /** Builds one floor's layout: a 3x2 grid of rooms carved into an
   *  otherwise solid grid, connected by a spanning tree of doors (plus
   *  one extra door for loop variety) so the whole floor is reachable
   *  through real doorways rather than open turnstile gaps. Built
   *  programmatically (not hand-typed ASCII art) — exact rectangle math,
   *  verified for connectivity by a standalone Node flood-fill script
   *  (treating door cells as passable, since they can always be opened)
   *  before ever being wired in here. */
  function buildFloorLayout(floorIndex) {
    const theme = FLOOR_THEMES[floorIndex];
    const archetype = archetypeFor(floorIndex);
    // Room size is the first and biggest lever on how a floor feels:
    // tunnels are cramped, datacenter/rooftop rooms are arenas.
    const roomW = archetype === ARCH_TUNNELS ? 4 + (floorIndex % 2) : 8 + (floorIndex % 2);
    const roomH = archetype === ARCH_TUNNELS ? 4 : 6 + (floorIndex % 2);
    const W = WALL + ROOM_COLS * (roomW + WALL);
    const H = WALL + ROOM_ROWS * (roomH + WALL);

    const grid = [];
    for (let r = 0; r < H; r++) grid.push(new Array(W).fill(1));

    function room(col, row) {
      const x0 = WALL + col * (roomW + WALL);
      const y0 = WALL + row * (roomH + WALL);
      return {
        x0, y0, x1: x0 + roomW - 1, y1: y0 + roomH - 1,
        cx: x0 + (roomW - 1) / 2, cy: y0 + (roomH - 1) / 2,
      };
    }

    for (let col = 0; col < ROOM_COLS; col++) {
      for (let row = 0; row < ROOM_ROWS; row++) {
        const rm = room(col, row);
        setBlock(grid, rm.y0, rm.x0, rm.y1, rm.x1, 0);
      }
    }

    // Decorative hazard-striped accents on the outer border only — never
    // touches an internal shared wall a door might need, so it can never
    // collide with door placement below.
    for (let c = 2; c < W - 2; c += 5) { grid[0][c] = 2; grid[H - 1][c] = 2; }

    const doorCells = [];
    function punchDoor(a2, b2, locked) {
      const [colA, rowA] = a2, [colB, rowB] = b2;
      const a = room(colA, rowA), b = room(colB, rowB);
      let doorCol, doorRow;
      if (rowA === rowB) {
        const left = colA < colB ? a : b;
        doorCol = left.x1 + 1;
        doorRow = Math.round((left.y0 + left.y1) / 2);
      } else {
        const top = rowA < rowB ? a : b;
        doorRow = top.y1 + 1;
        doorCol = Math.round((top.x0 + top.x1) / 2);
      }
      grid[doorRow][doorCol] = locked ? LOCKED_DOOR : 3;
      doorCells.push([doorCol, doorRow]);
      return [doorCol, doorRow];
    }

    for (let i = 0; i < ROOM_PATH.length - 1; i++) punchDoor(ROOM_PATH[i], ROOM_PATH[i + 1]);
    // One extra connection (alternating by floor) for a bit of loop
    // variety beyond the plain spanning-tree chain — kept keycard-locked
    // (see LOCKED_DOOR) since, unlike the spanning-tree doors, this one is
    // never required to reach any badge or the exit (every room is already
    // reachable without it), so gating it behind a keycard adds a genuine
    // "adventure game" objective with zero risk of blocking completion.
    const lockedDoorCell = punchDoor(
      floorIndex % 2 === 0 ? [0, 0] : [1, 0],
      floorIndex % 2 === 0 ? [0, 1] : [1, 1],
      true
    );

    const startRoom = room(0, 0);
    const exitRoom = room(0, 1);
    const midRooms = [room(1, 0), room(2, 0), room(2, 1), room(1, 1)];

    /* ---- Archetype interior features ----
       Everything below carves obstacles INSIDE already-open rooms, never
       into a shared wall or a door cell, so the spanning tree that makes
       the floor completable is untouched by any of it. Each obstacle also
       leaves at least one full-width lane clear along the room's edge, so
       no interior block can seal off a badge or a doorway. */
    const barrels = [];
    const snipers = [];
    const allRooms = [startRoom, ...midRooms, exitRoom];

    if (archetype === ARCH_TUNNELS) {
      // Interior pillars turn each small room into a pair of corridors.
      // Placed strictly on interior cells (never the room's outer ring),
      // so a lane always survives around them.
      //
      // The START room is deliberately skipped: at tunnel room sizes a
      // pillar there can land on (or flush against) the player's own
      // spawn tile, which spawns them embedded in a wall and unable to
      // move forward at all. Caught by the FPS regression suite's
      // "forward movement changes player position" check.
      allRooms.forEach((rm, i) => {
        if (rm === startRoom) return;
        if (rm.x1 - rm.x0 < 3 || rm.y1 - rm.y0 < 3) return;
        const pc = rm.x0 + 1 + (i % 2);
        const pr = rm.y0 + 1 + ((i + 1) % 2);
        if (pc < rm.x1 && pr < rm.y1) grid[pr][pc] = 1;
      });
    } else if (archetype === ARCH_DATACENTER) {
      // Server racks: 1x2 vertical blocks used as hard cover. Two per
      // mid-room, inset from the walls so the player can circle either
      // side of one and break a sniper's line of sight.
      midRooms.forEach((rm) => {
        const rackCols = [rm.x0 + 2, rm.x1 - 2];
        rackCols.forEach((c) => {
          const r0 = rm.y0 + 1;
          const r1 = Math.min(rm.y1 - 1, r0 + 1);
          if (c > rm.x0 && c < rm.x1 && r0 <= r1) setBlock(grid, r0, c, r1, c, 1);
        });
      });
      // One sniper per datacenter floor, holding the far arena from a
      // fixed post at the back of the deepest mid-room. Stationary by
      // design: the threat is the lock-on, not a chase.
      //
      // Posted on the room's CENTER column specifically: the rack columns
      // above are x0+2 and x1-2, and a room this wide always puts cx
      // strictly between them, so the sniper can never spawn embedded
      // inside its own cover (which would give it no line of sight to
      // anything and silently disable the whole mechanic).
      // (nearestOpenPoint is hoisted from below — it needs the finished
      // grid, which the rack pass above has just written.)
      const post = midRooms[1]; // room (2,0)
      const p1 = nearestOpenPoint(post.cx, post.y0 + 1.5, post);
      snipers.push({ x: p1.x, y: p1.y, angle: Math.PI / 2 });
      if (floorIndex >= 5) {
        const post2 = midRooms[2]; // room (2,1) — a second sniper late in the act
        const p2 = nearestOpenPoint(post2.cx, post2.y1 - 1.5, post2);
        snipers.push({ x: p2.x, y: p2.y, angle: -Math.PI / 2 });
      }
    } else {
      // ROOFTOP: no interior walls at all — an open arena to be held.
      // Explosive barrels are scattered one per room, away from the
      // player's spawn so the opening seconds are never a coin flip.
      allRooms.forEach((rm, i) => {
        if (rm === startRoom) return;
        const b = nearestOpenPoint(rm.x0 + 1.5 + (i % 2), rm.y0 + 1.5 + ((i + 1) % 2), rm);
        barrels.push({ x: b.x, y: b.y });
      });
    }

    /** Snaps a desired spawn point to the nearest genuinely-open cell in
     *  its own room. Necessary because the archetype pass above carves
     *  interior obstacles AFTER the rooms are hollowed out, and several
     *  of the entity positions below are corner-relative — a rack or a
     *  pillar can land exactly on one. Without this, a keycard could
     *  spawn inside a server rack: invisible, uncollectable, and (since
     *  the keycard gates a door) a silently broken objective. Found by a
     *  flood-fill reachability check over the live grid, which is now
     *  part of the FPS regression suite. */
    function nearestOpenPoint(px, py, rm) {
      const isOpen = (c, r) => r >= 0 && r < H && c >= 0 && c < W && grid[r][c] === 0;
      if (isOpen(Math.floor(px), Math.floor(py))) return { x: px, y: py };
      let best = null, bestD = Infinity;
      for (let r = rm.y0; r <= rm.y1; r++) {
        for (let c = rm.x0; c <= rm.x1; c++) {
          if (!isOpen(c, r)) continue;
          const cx = c + 0.5, cy = r + 0.5;
          const d = (cx - px) ** 2 + (cy - py) ** 2;
          if (d < bestD) { bestD = d; best = { x: cx, y: cy }; }
        }
      }
      return best || { x: rm.cx, y: rm.cy };
    }

    const exitCol = Math.round(exitRoom.cx);
    const exitRow = Math.round(exitRoom.cy);
    const exitCells = [[exitCol, exitRow], [exitCol + 1, exitRow]];

    const badges = midRooms.map((rm) => nearestOpenPoint(rm.x0 + 1.5, rm.y0 + 1.5, rm));

    // The floor's keycard (opens the locked door above) and two small
    // hidden caches — an ammo top-up and a health top-up — tucked into
    // corners of mid-rooms that never host a guard's start/waypoints,
    // away from each room's badge (top-left), so finding them takes an
    // actual detour without ever landing on top of another entity.
    const keycard = nearestOpenPoint(midRooms[0].x1 - 1.2, midRooms[0].y1 - 1.2, midRooms[0]); // room (1,0), bottom-right
    const secretHealth = nearestOpenPoint(midRooms[0].x1 - 1.2, midRooms[0].y0 + 1.2, midRooms[0]); // room (1,0), top-right
    const secretAmmo = nearestOpenPoint(midRooms[2].x1 - 1.2, midRooms[2].y1 - 1.2, midRooms[2]); // room (2,1), bottom-right

    const guardCount = floorIndex >= 5 ? 2 : 1; // floors 6-10 get a second guard
    const guardSpeed = 1.5 + floorIndex * 0.06; // steps up floor over floor
    const guards = [];
    const guardRoomA = midRooms[1]; // room (2,0)
    const guardAStart = nearestOpenPoint(guardRoomA.x1 - 1.5, guardRoomA.y1 - 1.5, guardRoomA);
    guards.push({
      x: guardAStart.x, y: guardAStart.y, speed: guardSpeed,
      // Tunnel guards hold a tight loop right by the room's doorway
      // corner rather than sweeping the whole room, which is what makes
      // them read as ambushers stepping out as you round a corner.
      waypoints: archetype === ARCH_TUNNELS
        ? [{ x: guardRoomA.x0 + 1.2, y: guardRoomA.y0 + 1.2 }, { x: guardRoomA.x0 + 1.2, y: guardRoomA.y1 - 1.2 }]
        : [{ x: guardRoomA.x0 + 1.2, y: guardRoomA.y1 - 1.2 }, { x: guardRoomA.x1 - 1.2, y: guardRoomA.y0 + 1.2 }],
      archetype,
    });
    if (guardCount === 2) {
      const guardRoomB = midRooms[3]; // room (1,1)
      guards.push({
        x: guardRoomB.x1 - 1.5, y: guardRoomB.y1 - 1.5, speed: guardSpeed,
        waypoints: [{ x: guardRoomB.x0 + 1.2, y: guardRoomB.y1 - 1.2 }, { x: guardRoomB.x1 - 1.2, y: guardRoomB.y0 + 1.2 }],
        archetype,
      });
    }

    // ROOFTOP only: the extraction hold-out. The exit stays sealed until
    // `seconds` elapse, while waves spawn on a fixed cadence in the mid-
    // rooms (never on top of the player). Spawn points are room centers,
    // which are guaranteed open floor on every archetype.
    const holdout = archetype === ARCH_ROOFTOP
      ? {
        seconds: HOLDOUT_BASE_SECONDS + (floorIndex - 7) * HOLDOUT_PER_FLOOR_SECONDS,
        waveInterval: WAVE_INTERVAL,
        spawnPoints: midRooms.map((rm) => ({ x: rm.cx, y: rm.cy })),
        enemySpeed: guardSpeed,
      }
      : null;

    // Snapped like every other entity — belt-and-braces even though the
    // start room is now kept clear of interior obstacles above.
    const startPos = nearestOpenPoint(startRoom.cx + 0.5, startRoom.cy + 0.5, startRoom);
    const playerStart = { x: startPos.x, y: startPos.y, angle: 0 };

    // Every floor now hides an optional hacking-terminal side-quest inside
    // the starting room, away from the player's spawn point and the door —
    // originally a Floor 1-only feature, generalized to every floor with
    // its own question drawn from TERMINAL_POOL so replaying later floors
    // doesn't just repeat the same puzzle.
    const terminalPos = nearestOpenPoint(startRoom.x0 + 1.5, startRoom.y1 - 1.5, startRoom);
    const terminal = {
      x: terminalPos.x, y: terminalPos.y,
      qa: TERMINAL_POOL[floorIndex % TERMINAL_POOL.length],
    };

    const pickups = [
      { x: keycard.x, y: keycard.y, type: "keycard" },
      { x: secretAmmo.x, y: secretAmmo.y, type: "ammo" },
      { x: secretHealth.x, y: secretHealth.y, type: "health" },
    ];

    // The last floor's exit is guarded by a dormant boss — see
    // activateFinalBoss() — that has to be stunned down (same paralyze()
    // targeting loop as an ordinary guard, see FpsBoss below) before the
    // floor can be cleared, so the FPS campaign ends in a real fight
    // instead of just a walk to the elevator.
    const boss = floorIndex === TOTAL_FLOORS - 1
      ? {
        name: "The Sentinel",
        x: exitRoom.cx, y: exitRoom.y0 + 1.3,
        speed: 2.1, maxHits: 3,
        waypoints: [{ x: exitRoom.x0 + 1.2, y: exitRoom.y0 + 1.3 }, { x: exitRoom.x1 - 1.2, y: exitRoom.y0 + 1.3 }],
      }
      : null;

    return {
      W, H, grid, exitCells, badges, guards, playerStart, doorCells, terminal,
      lockedDoorCell, pickups, boss,
      archetype, barrels, snipers, holdout,
      tint: theme.tint, name: theme.name,
    };
  }

  function isExitCell(col, row) {
    return currentExitCells.some(([c, r]) => c === col && r === row);
  }

  function doorAnimAt(c, r) {
    const d = doorStates.get(r + "," + c);
    return d ? d.anim : 0;
  }

  function isWall(x, y) {
    const c = Math.floor(x);
    const r = Math.floor(y);
    if (c < 0 || c >= currentW || r < 0 || r >= currentH) return true;
    const val = currentGrid[r][c];
    if (val === 0) return false;
    if (val === 3) return doorAnimAt(c, r) < 0.92;
    return true;
  }

  function wallTypeAt(x, y) {
    const c = Math.floor(x), r = Math.floor(y);
    if (c < 0 || c >= currentW || r < 0 || r >= currentH) return 1;
    return currentGrid[r][c];
  }

  /* ---------------- Texture tinting (once per floor, not per frame) ---- */
  function tintTexture(img, hexColor, brightness) {
    const w = img.naturalWidth || img.width;
    const h = img.naturalHeight || img.height;
    const off = document.createElement("canvas");
    off.width = w; off.height = h;
    const octx = off.getContext("2d");
    octx.drawImage(img, 0, 0, w, h);
    octx.globalCompositeOperation = "multiply";
    octx.fillStyle = hexColor;
    octx.fillRect(0, 0, w, h);
    octx.globalCompositeOperation = "destination-in";
    octx.drawImage(img, 0, 0, w, h);
    octx.globalCompositeOperation = "source-over";
    if (brightness != null && brightness !== 1) {
      octx.globalCompositeOperation = brightness < 1 ? "multiply" : "screen";
      octx.fillStyle = brightness < 1
        ? `rgba(0,0,0,${1 - brightness})`
        : `rgba(255,255,255,${Math.min(1, brightness - 1)})`;
      octx.fillRect(0, 0, w, h);
      octx.globalCompositeOperation = "source-over";
    }
    return off;
  }

  /* ---------------- Rendering constants ---------------- */
  const VIEW_W = 900;
  const VIEW_H = 600;
  const RAY_COLS = 300; // one ray per 3px column
  const STRIP_W = VIEW_W / RAY_COLS;
  const FOV = (66 * Math.PI) / 180;
  const PLANE_LEN = Math.tan(FOV / 2);
  const MAX_DEPTH = 30;
  const FLOOR_ROW_STEP = 2; // compute every other floor-cast row, duplicate — perf

  /* ---------------- Player / movement ---------------- */
  const MOVE_SPEED = 2.6;
  const TURN_SPEED = 2.6;
  const MOUSE_SENSITIVITY = 0.0022;
  const COLLIDE_RADIUS = 0.2;

  const STUN_CHARGES_START = 4;
  const STUN_CHARGES_CAP = 10; // ammo pickups can build a reserve up to this
  const STUN_RANGE = 5.0;
  const STUN_FOV = Math.PI / 10;
  const STUN_DURATION = 3.0;
  const TOUCH_RADIUS = 0.45;

  /* ---------------- Health, damage & pickups ---------------- */
  // Replaces the old "one touch = instant mission over": a guard's touch
  // now costs health, with a brief invulnerability window after each hit
  // so standing in a guard's path doesn't melt the player in a single
  // frame — real risk of dying rather than an instant, un-telegraphed one.
  const PLAYER_MAX_HEALTH = 100;
  const DAMAGE_PER_HIT = 25;
  const HURT_INVULN = 0.9;
  const PICKUP_RADIUS = 0.45;
  const AMMO_PICKUP_GAIN = 3;
  const HEALTH_PICKUP_GAIN = 35;

  /* ---------------- Doors ---------------- */
  const DOOR_OPEN_RADIUS = 1.6; // any mover this close to a door's center opens it
  const DOOR_AUTO_CLOSE_DELAY = 2.5; // seconds after the last mover leaves before it closes
  const DOOR_ANIM_SPEED = 2.4; // full open/close sweep in ~1/DOOR_ANIM_SPEED seconds

  /* ---------------- Hacking terminal side-quest ---------------- */
  const INTERACT_RADIUS = 1.7;
  // One entry per floor (cycled via floorIndex % length so a 10-floor run
  // never repeats a question back-to-back) — every floor's terminal picks
  // its own { question, options, correct } from here instead of the old
  // single Floor-1-only hardcoded puzzle.
  const TERMINAL_POOL = [
    {
      question: "Which command lists active badge sessions without tripping the audit log?",
      options: ["DROP TABLE badge_log;", "sessions --list --readonly", "mail --all badge_log.csv", "rm -rf /var/log/badges"],
      correct: 1,
    },
    {
      question: "A guard's badge reader is left logged in and unattended. What's the safest first move?",
      options: ["Use it to print yourself a badge", "Lock the session and report it", "Leave it as-is, it's not your problem", "Unplug it from the wall"],
      correct: 1,
    },
    {
      question: "Which of these is the strongest password?",
      options: ["Summer2024!", "correct-horse-battery-staple-42", "P@ssw0rd", "CompanyName123"],
      correct: 1,
    },
    {
      question: "You find a USB drive labeled \"Payroll — CONFIDENTIAL\" on the floor. What should you do?",
      options: ["Plug it in to see what's on it", "Hand it to security, unopened", "Take it home to check later", "Leave it exactly where it lies"],
      correct: 1,
    },
    {
      question: "Which network traffic pattern is the clearest sign of data exfiltration?",
      options: ["A large upload to an unfamiliar external host at 3 AM", "Normal business-hours email traffic", "A routine software update download", "Internal traffic between two known servers"],
      correct: 0,
    },
  ];

  /* ---------------- Module state ---------------- */
  const el = {};
  let bound = false;
  let canvas, ctx, mmCanvas, mmCtx;
  let rafId = null;
  let lastTime = 0;
  let state = "idle"; // idle | loading | playing | terminal | gameover | victory
  let startTime = 0;

  let floorIndex = 0;
  let currentGrid, currentW, currentH, currentExitCells, currentTint, currentFloorName;
  let wallTexLight, wallTexDark, hazardTexLight, hazardTexDark, doorTexLight, doorTexDark;
  let floorTexLightData, floorTexDarkData;

  let posX, posY, angle;
  let dirX, dirY, planeX, planeY;
  let badges = [];
  let badgesCollected = 0;
  let stunCharges = STUN_CHARGES_START;
  let stunFlashTime = 0;
  let gunFireTime = 0; // >0 while the muzzle-flash weapon frame should show
  let bobPhase = 0;
  let guards = [];
  let doorStates = new Map(); // "row,col" -> { open, closeTimer, anim }
  let currentTerminal = null; // { x, y, hacked, qa } — every floor has one now
  let pointerLocked = false;

  let playerHealth = PLAYER_MAX_HEALTH;
  let hurtCooldownT = 0; // invulnerability window after the last hit
  let hurtFlashTime = 0; // brief red screen-flash on a hit
  let hasKeycard = false;
  let currentLockedDoorCell = null; // [col, row] — the keycard-gated door, or null
  let pickups = []; // { x, y, type: "keycard"|"ammo"|"health", collected }
  let currentBoss = null; // FpsBoss instance on the final floor, else null
  // ---- Level archetype state (see archetypeFor()) ----
  let currentArchetype = ARCH_TUNNELS;
  let snipers = [];   // FpsSniper instances (datacenter floors); also pushed into `guards`
  let barrels = [];   // { x, y, exploded, flashT } (rooftop floors)
  let holdout = null; // rooftop extraction timer + wave spawner, else null

  const zBuffer = new Array(RAY_COLS).fill(MAX_DEPTH);

  function cacheDom() {
    el.canvas = document.getElementById("fpsCanvas");
    el.minimap = document.getElementById("fpsMinimap");
    el.overlay = document.getElementById("fpsOverlay");
    el.hudPlayerName = document.getElementById("fpsHudPlayerName");
    el.hudBadges = document.getElementById("fpsHudBadges");
    el.hudStun = document.getElementById("fpsHudStun");
    el.hudHealth = document.getElementById("fpsHudHealth");
    el.hudKeycard = document.getElementById("fpsHudKeycard");
    el.hudFloorNum = document.getElementById("fpsHudFloorNum");
    el.hudFloorName = document.getElementById("fpsHudFloorName");
    el.btnMute = document.getElementById("fpsBtnMute");
    el.volumeSlider = document.getElementById("fpsVolumeSlider");
  }

  function bindPersistentEvents() {
    if (bound) return;
    bound = true;
    el.btnMute.addEventListener("click", () => {
      const nowMuted = !window.CG.audio.muted;
      window.CG.audio.setMuted(nowMuted);
      el.btnMute.textContent = nowMuted ? "🔇 Muted" : "🔊 Sound";
      el.btnMute.setAttribute("aria-pressed", String(nowMuted));
    });
    el.volumeSlider.addEventListener("input", (e) => {
      window.CG.audio.setVolume(Number(e.target.value) / 100);
    });
    UI.bindFullscreenToggle("fpsBtnFullscreen", "screen-fps");
    bindPad("fpsPadLeft", "left");
    bindPad("fpsPadUp", "up");
    bindPad("fpsPadDown", "down");
    bindPad("fpsPadRight", "right");
    bindFirePad("fpsPadFire");
    bindInteractPad("fpsPadInteract");

    // Mouse-look: click the canvas to lock the pointer (movementX then
    // steers the view every frame); click again once locked to fire.
    // Esc (the browser's own pointer-lock-release gesture) falls back to
    // keyboard-only turning until the canvas is clicked again.
    el.canvas.addEventListener("click", () => {
      if (state !== "playing") return;
      if (document.pointerLockElement !== el.canvas) {
        el.canvas.requestPointerLock();
      } else {
        window.CG.input.fire = true;
      }
    });
    document.addEventListener("pointerlockchange", () => {
      pointerLocked = document.pointerLockElement === el.canvas;
    });
    document.addEventListener("mousemove", (e) => {
      if (!pointerLocked || state !== "playing") return;
      angle += e.movementX * MOUSE_SENSITIVITY;
      if (angle > Math.PI) angle -= Math.PI * 2;
      if (angle < -Math.PI) angle += Math.PI * 2;
      updateDirPlane();
    });
  }

  function bindPad(id, dir) {
    const padEl = document.getElementById(id);
    if (!padEl) return;
    const set = (val) => (e) => { e.preventDefault(); window.CG.input[dir] = val; };
    padEl.addEventListener("pointerdown", set(true));
    padEl.addEventListener("pointerup", set(false));
    padEl.addEventListener("pointerleave", set(false));
    padEl.addEventListener("pointercancel", set(false));
  }

  function bindFirePad(id) {
    const padEl = document.getElementById(id);
    if (!padEl) return;
    padEl.addEventListener("pointerdown", (e) => { e.preventDefault(); window.CG.input.fire = true; });
  }

  function bindInteractPad(id) {
    const padEl = document.getElementById(id);
    if (!padEl) return;
    padEl.addEventListener("pointerdown", (e) => { e.preventDefault(); window.CG.input.interact = true; });
  }

  /* ---------------- FpsGuard: lightweight 2D patrol/chase/paralyze ---------------- */
  class FpsGuard {
    constructor(x, y, waypoints, speed) {
      this.x = x;
      this.y = y;
      this.waypoints = waypoints;
      this.wpIndex = 0;
      this.speed = speed || 1.5;
      this.chaseSpeed = this.speed * 1.55;
      this.paralyzed = 0;
      this.alert = false;
      this.sightRange = 7.0;
      // Detection is a forward-facing cone, not omniscient — a guard
      // patrolling east-west won't spot a player approaching from
      // directly behind it. closeRadius is a small point-blank exception.
      this.facingAngle = Math.PI;
      this.sightHalfFov = Math.PI / 4;
      this.closeRadius = 1.3;
      this.animPhase = 0;
    }

    hasLineOfSight(tx, ty) {
      const dx = tx - this.x;
      const dy = ty - this.y;
      const dist = Math.hypot(dx, dy);
      if (dist > this.sightRange) return false;
      const steps = Math.ceil(dist * 4);
      for (let i = 1; i < steps; i++) {
        const t = i / steps;
        if (isWall(this.x + dx * t, this.y + dy * t)) return false;
      }
      return true;
    }

    canDetect(px, py) {
      const dx = px - this.x;
      const dy = py - this.y;
      const dist = Math.hypot(dx, dy);
      if (dist > this.sightRange) return false;
      if (!this.hasLineOfSight(px, py)) return false;
      if (dist <= this.closeRadius) return true;
      const angleToTarget = Math.atan2(dy, dx);
      let diff = angleToTarget - this.facingAngle;
      while (diff > Math.PI) diff -= Math.PI * 2;
      while (diff < -Math.PI) diff += Math.PI * 2;
      return Math.abs(diff) <= this.sightHalfFov;
    }

    update(dt, playerX, playerY) {
      if (this.paralyzed > 0) {
        this.paralyzed = Math.max(0, this.paralyzed - dt);
        return;
      }

      const canSeePlayer = this.canDetect(playerX, playerY);
      if (canSeePlayer) this.alert = true;

      let tx, ty, speed;
      if (this.alert && canSeePlayer) {
        tx = playerX; ty = playerY; speed = this.chaseSpeed;
      } else {
        const wp = this.waypoints[this.wpIndex];
        tx = wp.x; ty = wp.y; speed = this.speed;
        if (Math.hypot(tx - this.x, ty - this.y) < 0.15) {
          this.wpIndex = (this.wpIndex + 1) % this.waypoints.length;
        }
      }

      const dx = tx - this.x;
      const dy = ty - this.y;
      const dist = Math.hypot(dx, dy);
      if (dist > 0.02) {
        this.facingAngle = Math.atan2(dy, dx);
        this.animPhase += dt * speed * 3;
        const stepX = (dx / dist) * speed * dt;
        const stepY = (dy / dist) * speed * dt;
        if (!isWall(this.x + stepX, this.y)) this.x += stepX;
        if (!isWall(this.x, this.y + stepY)) this.y += stepY;
      }
    }

    paralyze(duration) {
      this.paralyzed = duration;
    }
  }

  /* ---------------- FpsSniper: the Datacenter archetype's cover-shooter threat ----
     A stationary enemy that never chases. When it has line of sight to
     the player it paints a laser sight and holds the lock for
     SNIPER_LOCK_TIME; if the lock survives to the end, it fires for real
     damage. BREAKING LINE OF SIGHT CANCELS THE LOCK — that single rule is
     what turns the datacenter floors into cover-shooter rooms, because the
     server racks placed in buildFloorLayout() are exactly the thing that
     breaks it. A stun shot paralyzes it like any guard, which also drops
     the lock. It has a full 360° awareness on purpose (it's scanning, not
     patrolling), so the counter is cover, never approaching from behind. */
  class FpsSniper extends FpsGuard {
    constructor(x, y, angle) {
      // Waypoints are its own position — it never moves, but the base
      // class's update() still expects a non-empty waypoint list.
      super(x, y, [{ x, y }], 0);
      this.isSniper = true;
      this.facingAngle = angle || 0;
      this.sightRange = SNIPER_RANGE;
      this.sightHalfFov = Math.PI;  // scans all directions
      this.lockT = 0;               // seconds of uninterrupted lock so far
      this.cooldownT = 0;
      this.firedFlash = 0;          // brief visual after a shot lands
      this.hasLock = false;
    }

    /** Returns true on the frame it actually fires, so the caller can
     *  apply damage (update() has no access to player health directly). */
    updateSniper(dt, playerX, playerY) {
      if (this.firedFlash > 0) this.firedFlash = Math.max(0, this.firedFlash - dt);
      if (this.paralyzed > 0) {
        this.paralyzed = Math.max(0, this.paralyzed - dt);
        this.lockT = 0;
        this.hasLock = false;
        return false;
      }
      if (this.cooldownT > 0) this.cooldownT = Math.max(0, this.cooldownT - dt);

      const sees = this.hasLineOfSight(playerX, playerY);
      this.hasLock = sees && this.cooldownT <= 0;
      if (!this.hasLock) {
        // Cover broke the lock (or it's reloading) — the charge resets
        // completely rather than pausing, so ducking behind a rack is a
        // real reset and not just a delay.
        this.lockT = 0;
        return false;
      }
      this.alert = true;
      this.facingAngle = Math.atan2(playerY - this.y, playerX - this.x);
      this.lockT += dt;
      if (this.lockT >= SNIPER_LOCK_TIME) {
        this.lockT = 0;
        this.cooldownT = SNIPER_COOLDOWN;
        this.firedFlash = 0.25;
        return true;
      }
      return false;
    }

    /** How far through its lock it is, 0..1 — drives the laser sight's
     *  brightness/thickness so the player can read how long they have. */
    get lockRatio() {
      return Math.max(0, Math.min(1, this.lockT / SNIPER_LOCK_TIME));
    }

    // Never moves; the base update() would try to walk it to its own
    // position and recompute facing, which would fight updateSniper().
    update() { /* intentionally inert — see updateSniper() */ }
  }

  /* ---------------- FpsBoss: Floor 10's exit guardian ---------------- */
  // Reuses all of FpsGuard's patrol/chase/detect/paralyze plumbing — the
  // only real differences: it takes `maxHits` separate paralyze() hits
  // before it's actually defeated (the first hits still apply a normal
  // temporary freeze, same window-of-opportunity a stun hit gives against
  // an ordinary guard), it doesn't move once defeated, and it's kept out
  // of the `guards` array entirely until activateFinalBoss() wakes it —
  // see update()'s badge-collection check — so it can't be touched, seen,
  // or chased into before that.
  class FpsBoss extends FpsGuard {
    constructor(x, y, waypoints, speed, opts) {
      super(x, y, waypoints, speed);
      opts = opts || {};
      this.isBoss = true;
      this.name = opts.name || "The Sentinel";
      this.maxHits = opts.maxHits || 3;
      this.hitsTaken = 0;
      this.defeated = false;
      this.sightRange = 9.0;
      this.sightHalfFov = Math.PI / 2.1;
      this.chaseSpeed = speed * 1.8;
      this.awake = false; // flips true in update()'s badge-collection check — see activateFinalBoss note there
    }

    paralyze(duration) {
      if (this.defeated) return;
      this.hitsTaken++;
      if (this.hitsTaken >= this.maxHits) {
        this.defeated = true;
        this.paralyzed = 0;
        this.alert = false;
      } else {
        super.paralyze(duration);
      }
    }

    update(dt, playerX, playerY) {
      if (this.defeated) return;
      super.update(dt, playerX, playerY);
    }
  }

  /* ---------------- Lifecycle ---------------- */
  function start() {
    cacheDom();
    canvas = el.canvas;
    ctx = canvas.getContext("2d");
    mmCanvas = el.minimap;
    mmCtx = mmCanvas.getContext("2d");
    bindPersistentEvents();

    window.CG.audio.unlock();
    window.CG.audio.startMusic();

    window.CG.input.up = window.CG.input.down = window.CG.input.left = window.CG.input.right = false;
    window.CG.input.fire = false;
    window.CG.input.interact = false;

    el.hudPlayerName.textContent = window.CG.getPlayerName();

    window.FpsModeActive = true;
    floorIndex = 0;
    stunCharges = STUN_CHARGES_START;
    playerHealth = PLAYER_MAX_HEALTH;
    hurtCooldownT = 0;
    hurtFlashTime = 0;
    state = "loading";
    startTime = performance.now();
    UI.showScreen("screen-fps");
    ensureImagesThenBuild(floorIndex, () => {
      state = "playing";
      lastTime = performance.now();
      if (rafId) cancelAnimationFrame(rafId);
      rafId = requestAnimationFrame(loop);
    });
  }

  function restart() {
    start();
  }

  function ensureImagesThenBuild(idx, cb) {
    const imgs = [IMG_WALL_PANEL, IMG_WALL_HAZARD, IMG_FLOOR_TILE, IMG_GUN_HAND, IMG_DOOR, IMG_TERMINAL];
    if (imgs.every((im) => im.complete && im.naturalWidth > 0)) {
      buildLevel(idx);
      cb();
    } else {
      requestAnimationFrame(() => ensureImagesThenBuild(idx, cb));
    }
  }

  function buildLevel(idx) {
    const layout = buildFloorLayout(idx);
    currentGrid = layout.grid;
    currentW = layout.W;
    currentH = layout.H;
    currentExitCells = layout.exitCells;
    currentTint = layout.tint;
    currentFloorName = layout.name;

    posX = layout.playerStart.x;
    posY = layout.playerStart.y;
    angle = layout.playerStart.angle;
    updateDirPlane();

    badges = layout.badges.map((b) => ({ x: b.x, y: b.y, collected: false }));
    badgesCollected = 0;

    guards = layout.guards.map((g) => {
      const guard = new FpsGuard(g.x, g.y, g.waypoints, g.speed);
      if (g.archetype === ARCH_TUNNELS) {
        // Ambush tuning: can't see far down a corridor, but reacts to
        // anything that rounds the corner into it — a much wider cone and
        // a bigger point-blank radius than the open-floor default.
        guard.sightRange = 4.2;
        guard.sightHalfFov = Math.PI / 2;
        guard.closeRadius = 2.0;
        guard.chaseSpeed = guard.speed * 1.9;
      }
      return guard;
    });

    // ---- Archetype state ----
    currentArchetype = layout.archetype || ARCH_TUNNELS;
    snipers = (layout.snipers || []).map((s) => new FpsSniper(s.x, s.y, s.angle));
    snipers.forEach((s) => guards.push(s)); // so stun targeting/drawing pick them up for free
    barrels = (layout.barrels || []).map((b) => ({ x: b.x, y: b.y, exploded: false, flashT: 0 }));
    holdout = layout.holdout
      ? {
        total: layout.holdout.seconds,
        timeLeft: layout.holdout.seconds,
        waveInterval: layout.holdout.waveInterval,
        waveTimer: layout.holdout.waveInterval,
        wave: 0,
        spawnPoints: layout.holdout.spawnPoints,
        enemySpeed: layout.holdout.enemySpeed,
        complete: false,
      }
      : null;

    doorStates = new Map();
    layout.doorCells.forEach(([c, r]) => {
      doorStates.set(r + "," + c, { open: false, closeTimer: 0, anim: 0 });
    });

    currentTerminal = layout.terminal ? { x: layout.terminal.x, y: layout.terminal.y, hacked: false, qa: layout.terminal.qa } : null;

    hasKeycard = false;
    currentLockedDoorCell = layout.lockedDoorCell || null;
    pickups = (layout.pickups || []).map((pk) => ({ x: pk.x, y: pk.y, type: pk.type, collected: false }));
    currentBoss = layout.boss
      ? new FpsBoss(layout.boss.x, layout.boss.y, layout.boss.waypoints, layout.boss.speed, { name: layout.boss.name, maxHits: layout.boss.maxHits })
      : null;
    hurtCooldownT = 0;
    hurtFlashTime = 0;

    rebuildTexturesForFloor(currentTint);

    window.CG.input.up = window.CG.input.down = window.CG.input.left = window.CG.input.right = false;
    window.CG.input.fire = false;
    window.CG.input.interact = false;

    el.hudFloorNum.textContent = `Floor ${idx + 1}/${TOTAL_FLOORS}`;
    // The archetype is surfaced alongside the department name so the
    // player knows which set of rules this floor plays by before they
    // walk into it (tight corridors vs. cover-shooter vs. hold-out).
    el.hudFloorName.textContent = `${currentFloorName} · ${ARCHETYPE_LABEL[currentArchetype]}`;
    updateHud();
  }

  function rebuildTexturesForFloor(tint) {
    wallTexLight = tintTexture(IMG_WALL_PANEL, tint, 1.0);
    wallTexDark = tintTexture(IMG_WALL_PANEL, tint, 0.7);
    hazardTexLight = tintTexture(IMG_WALL_HAZARD, "#ffffff", 1.0); // used as-is, universal
    hazardTexDark = tintTexture(IMG_WALL_HAZARD, "#ffffff", 0.7);
    doorTexLight = tintTexture(IMG_DOOR, "#ffffff", 1.0); // used as-is, universal like the hazard texture
    doorTexDark = tintTexture(IMG_DOOR, "#ffffff", 0.7);
    const floorLightCanvas = tintTexture(IMG_FLOOR_TILE, tint, 1.0);
    const floorDarkCanvas = tintTexture(IMG_FLOOR_TILE, tint, 0.66);
    floorTexLightData = floorLightCanvas.getContext("2d").getImageData(0, 0, FLOOR_TEX_SIZE, FLOOR_TEX_SIZE).data;
    floorTexDarkData = floorDarkCanvas.getContext("2d").getImageData(0, 0, FLOOR_TEX_SIZE, FLOOR_TEX_SIZE).data;
  }

  function updateDirPlane() {
    dirX = Math.cos(angle);
    dirY = Math.sin(angle);
    planeX = -Math.sin(angle) * PLANE_LEN;
    planeY = Math.cos(angle) * PLANE_LEN;
  }

  function updateHud() {
    el.hudBadges.textContent = `${badgesCollected}/${badges.length}`;
    el.hudStun.textContent = String(stunCharges);
    if (el.hudHealth) el.hudHealth.textContent = String(Math.max(0, Math.round(playerHealth)));
    if (el.hudKeycard) el.hudKeycard.textContent = hasKeycard ? "Held" : "—";
  }

  /* ---------------- Loop ---------------- */
  function loop(now) {
    const dt = Math.min(0.05, (now - lastTime) / 1000);
    lastTime = now;

    if (state === "playing") {
      update(dt);
      render();
    }

    if (state === "playing") rafId = requestAnimationFrame(loop);
  }

  function update(dt) {
    const input = window.CG.input;

    // Turning: mouse-look (pointerlockchange/mousemove above) drives angle
    // directly whenever the pointer is locked, so Left/Right are freed up
    // to strafe instead. Falls back to keyboard-only turning otherwise.
    if (pointerLocked) {
      let strafe = 0;
      if (input.left) strafe -= 1;
      if (input.right) strafe += 1;
      if (strafe !== 0) {
        const strafeX = -dirY * strafe * MOVE_SPEED * dt;
        const strafeY = dirX * strafe * MOVE_SPEED * dt;
        tryMove(strafeX, strafeY);
        bobPhase += dt * 9;
      }
    } else {
      if (input.left) angle -= TURN_SPEED * dt;
      if (input.right) angle += TURN_SPEED * dt;
      if (angle > Math.PI) angle -= Math.PI * 2;
      if (angle < -Math.PI) angle += Math.PI * 2;
    }
    updateDirPlane();

    let moveDir = 0;
    if (input.up) moveDir += 1;
    if (input.down) moveDir -= 1;
    if (moveDir !== 0) {
      const stepX = dirX * moveDir * MOVE_SPEED * dt;
      const stepY = dirY * moveDir * MOVE_SPEED * dt;
      tryMove(stepX, stepY);
      bobPhase += dt * 9;
    }

    if (input.fire) {
      input.fire = false;
      tryFireStun();
    }

    if (input.interact) {
      input.interact = false;
      tryInteract();
      if (state !== "playing") return;
    }

    if (stunFlashTime > 0) stunFlashTime = Math.max(0, stunFlashTime - dt);
    if (gunFireTime > 0) gunFireTime = Math.max(0, gunFireTime - dt);
    if (hurtCooldownT > 0) hurtCooldownT = Math.max(0, hurtCooldownT - dt);
    if (hurtFlashTime > 0) hurtFlashTime = Math.max(0, hurtFlashTime - dt);

    updateDoors(dt);
    guards.forEach((g) => g.update(dt, posX, posY));

    // ---- Datacenter archetype: sniper lock-on ----
    // Runs after ordinary guard movement so a sniper's line-of-sight test
    // sees this frame's real world state. A fired shot applies damage
    // immediately, bypassing hurtCooldownT (that window exists to stop
    // melee contact from melting the bar frame-by-frame; a sniper already
    // rate-limits itself with SNIPER_COOLDOWN).
    for (const s of snipers) {
      if (s.updateSniper(dt, posX, posY)) {
        playerHealth = Math.max(0, playerHealth - SNIPER_DAMAGE);
        hurtFlashTime = 0.4;
        window.CG.audio.playHit();
        updateHud();
        if (playerHealth <= 0) { failMission(); return; }
      }
    }

    // ---- Rooftop archetype: extraction hold-out + waves ----
    if (holdout && !holdout.complete) {
      holdout.timeLeft = Math.max(0, holdout.timeLeft - dt);
      holdout.waveTimer -= dt;
      if (holdout.waveTimer <= 0) {
        holdout.waveTimer = holdout.waveInterval;
        spawnWave();
      }
      if (holdout.timeLeft <= 0) {
        holdout.complete = true;
        window.CG.audio.playCheckpoint();
        updateHud();
      }
    }
    if (barrels.length) updateBarrels(dt);

    // A guard's touch now costs health instead of ending the run outright
    // — HURT_INVULN gives a brief breather after each hit so standing in
    // a guard's path for a couple of frames doesn't melt the player
    // instantly. A defeated boss (see FpsBoss) is permanently safe, same
    // as a paralyzed guard; `g.defeated` is simply undefined (falsy) on
    // every ordinary guard, so this is a no-op check for those.
    if (hurtCooldownT <= 0) {
      for (const g of guards) {
        if (g.paralyzed <= 0 && !g.defeated && Math.hypot(g.x - posX, g.y - posY) < TOUCH_RADIUS) {
          playerHealth = Math.max(0, playerHealth - DAMAGE_PER_HIT);
          hurtCooldownT = HURT_INVULN;
          hurtFlashTime = 0.35;
          window.CG.audio.playHit();
          updateHud();
          if (playerHealth <= 0) { failMission(); return; }
          break;
        }
      }
    }

    badges.forEach((b) => {
      if (!b.collected && Math.hypot(b.x - posX, b.y - posY) < 0.4) {
        b.collected = true;
        badgesCollected++;
        window.CG.audio.playCollect();
        updateHud();
      }
    });

    pickups.forEach((pk) => {
      if (pk.collected || Math.hypot(pk.x - posX, pk.y - posY) >= PICKUP_RADIUS) return;
      pk.collected = true;
      if (pk.type === "keycard") {
        hasKeycard = true;
        // Converts the locked cell into an ordinary auto-open door — its
        // doorStates entry already exists (every doorCell, locked or not,
        // gets one in buildLevel()), so it immediately behaves exactly
        // like any other door the moment the player walks up to it.
        if (currentLockedDoorCell) {
          const [lc, lr] = currentLockedDoorCell;
          currentGrid[lr][lc] = 3;
        }
      } else if (pk.type === "ammo") {
        stunCharges = Math.min(STUN_CHARGES_CAP, stunCharges + AMMO_PICKUP_GAIN);
      } else if (pk.type === "health") {
        playerHealth = Math.min(PLAYER_MAX_HEALTH, playerHealth + HEALTH_PICKUP_GAIN);
      }
      window.CG.audio.playCollect();
      updateHud();
    });

    // The final floor's Sentinel wakes the instant every badge is in —
    // same "dormant until the real objective is done" shape as Story
    // Mode's Floor 5 boss — and from then on blocks the win until defeated.
    if (currentBoss && !currentBoss.awake && badgesCollected >= badges.length) {
      currentBoss.awake = true;
      guards.push(currentBoss);
      window.CG.audio.playCheckpoint();
    }

    const col = Math.floor(posX);
    const row = Math.floor(posY);
    const bossClear = !currentBoss || currentBoss.defeated;
    // On a rooftop floor the extraction timer is an additional gate on top
    // of badges and the boss: the exit is sealed until the hold-out ends,
    // which is what makes those floors a survival objective rather than a
    // faster version of "find everything and leave".
    const holdoutClear = !holdout || holdout.complete;
    if (badgesCollected >= badges.length && bossClear && holdoutClear && isExitCell(col, row)) {
      advanceFloor();
    }
  }

  /** Doors slide open for any mover (the player, or a guard mid-chase)
   *  standing near their center, and auto-close a short delay after the
   *  last one leaves — classic Wolfenstein-3D door behavior. Only the
   *  player's proximity is checked (guards in this layout patrol within a
   *  single room and never approach a door on their own patrol route; a
   *  chasing guard can still walk through one the player opened, since
   *  isWall() consults the same live anim value). */
  function updateDoors(dt) {
    doorStates.forEach((d, key) => {
      const [r, c] = key.split(",").map(Number);
      const cx = c + 0.5, cy = r + 0.5;
      const dist = Math.hypot(posX - cx, posY - cy);
      if (dist < DOOR_OPEN_RADIUS) {
        d.open = true;
        d.closeTimer = DOOR_AUTO_CLOSE_DELAY;
      } else if (d.open) {
        d.closeTimer -= dt;
        if (d.closeTimer <= 0) d.open = false;
      }
      const target = d.open ? 1 : 0;
      const step = DOOR_ANIM_SPEED * dt;
      if (d.anim < target) d.anim = Math.min(target, d.anim + step);
      else if (d.anim > target) d.anim = Math.max(target, d.anim - step);
    });
  }

  function tryMove(stepX, stepY) {
    const nx = posX + stepX;
    const ny = posY + stepY;
    if (!isWall(nx + Math.sign(stepX) * COLLIDE_RADIUS, posY) && !isWall(nx - Math.sign(stepX) * COLLIDE_RADIUS, posY)) {
      posX = nx;
    }
    if (!isWall(posX, ny + Math.sign(stepY) * COLLIDE_RADIUS) && !isWall(posX, ny - Math.sign(stepY) * COLLIDE_RADIUS)) {
      posY = ny;
    }
  }

  function tryFireStun() {
    if (stunCharges <= 0) return;
    let target = null;
    let bestDist = Infinity;
    for (const g of guards) {
      if (g.defeated) continue; // a defeated boss (see FpsBoss) is a spent target
      const dx = g.x - posX;
      const dy = g.y - posY;
      const dist = Math.hypot(dx, dy);
      if (dist > STUN_RANGE) continue;
      const targetAngle = Math.atan2(dy, dx);
      let diff = targetAngle - angle;
      while (diff > Math.PI) diff -= Math.PI * 2;
      while (diff < -Math.PI) diff += Math.PI * 2;
      if (Math.abs(diff) > STUN_FOV) continue;
      if (!g.hasLineOfSight(posX, posY)) continue;
      if (dist < bestDist) { bestDist = dist; target = g; }
    }

    // A live barrel in the same cone, NEARER than the best guard target,
    // is what the shot actually hits — so on rooftop floors the player can
    // deliberately aim past an enemy at the barrel behind it. Checked
    // after guard targeting so the comparison is against a real distance.
    let barrelTarget = null;
    let barrelDist = Infinity;
    for (const b of barrels) {
      if (b.exploded) continue;
      const dx = b.x - posX, dy = b.y - posY;
      const dist = Math.hypot(dx, dy);
      if (dist > STUN_RANGE) continue;
      let diff = Math.atan2(dy, dx) - angle;
      while (diff > Math.PI) diff -= Math.PI * 2;
      while (diff < -Math.PI) diff += Math.PI * 2;
      if (Math.abs(diff) > STUN_FOV) continue;
      if (dist < barrelDist) { barrelDist = dist; barrelTarget = b; }
    }

    gunFireTime = 0.18;
    window.CG.audio.playHit();

    if (barrelTarget && barrelDist <= bestDist) {
      stunCharges--;
      stunFlashTime = 0.15;
      detonateBarrel(barrelTarget);
      updateHud();
      return;
    }

    if (!target) return;

    stunCharges--;
    target.paralyze(STUN_DURATION);
    stunFlashTime = 0.15;
    updateHud();
  }

  /** Opens the current floor's hacking-terminal mini-puzzle if the player
   *  is close enough and it hasn't already been solved. No-ops otherwise
   *  (walking up and pressing E away from the terminal is silently
   *  ignored — this is an optional side objective, never a required gate,
   *  on every floor). */
  function tryInteract() {
    if (!currentTerminal || currentTerminal.hacked) return;
    const dist = Math.hypot(currentTerminal.x - posX, currentTerminal.y - posY);
    if (dist > INTERACT_RADIUS) return;
    openTerminalPuzzle();
  }

  function openTerminalPuzzle() {
    state = "terminal";
    setFpsOverlayVisible(true);
    const qa = currentTerminal.qa;
    const optsHtml = qa.options.map((opt, i) => `
      <button class="btn btn-secondary fps-terminal-opt" data-i="${i}" type="button">
        <span class="fps-terminal-letter">${String.fromCharCode(65 + i)}</span>${escapeHtmlLocal(opt)}
      </button>`).join("");
    el.overlay.innerHTML = `
      <div class="story-panel">
        <div class="eyebrow">Side Objective &middot; Floor Terminal</div>
        <h2 class="title">Hack the Terminal</h2>
        <p class="story-copy">${escapeHtmlLocal(qa.question)}</p>
        <div class="fps-terminal-opts">${optsHtml}</div>
        <p class="terminal-feedback" id="fpsTerminalFeedback">No penalty for a wrong guess — try again.</p>
        <div class="btn-row">
          <button class="btn btn-secondary" id="fpsTerminalClose" type="button">Walk Away</button>
        </div>
      </div>`;
    el.overlay.querySelectorAll(".fps-terminal-opt").forEach((btn) => {
      btn.addEventListener("click", () => handleTerminalGuess(Number(btn.dataset.i)));
    });
    document.getElementById("fpsTerminalClose").addEventListener("click", closeTerminalPuzzle);
  }

  function handleTerminalGuess(i) {
    if (i === currentTerminal.qa.correct) {
      currentTerminal.hacked = true;
      stunCharges = Math.min(STUN_CHARGES_CAP, stunCharges + 1);
      updateHud();
      window.CG.audio.playCollect();
      closeTerminalPuzzle();
    } else {
      window.CG.audio.playHit();
      const fb = document.getElementById("fpsTerminalFeedback");
      if (fb) fb.textContent = "Access denied — that command trips the audit log. Try another.";
    }
  }

  function closeTerminalPuzzle() {
    setFpsOverlayVisible(false);
    if (state === "gameover" || state === "victory") return;
    state = "playing";
    lastTime = performance.now();
    if (rafId) cancelAnimationFrame(rafId);
    rafId = requestAnimationFrame(loop);
  }

  function setFpsOverlayVisible(visible) {
    el.overlay.classList.toggle("active", visible);
    canvas.style.visibility = visible ? "hidden" : "visible";
  }

  function escapeHtmlLocal(str) {
    const div = document.createElement("div");
    div.textContent = str;
    return div.innerHTML;
  }

  /** Rooftop archetype: drops a wave of attackers at the arena's spawn
   *  points. Wave size grows every wave, and each wave is slightly faster
   *  than the last, so holding out gets genuinely harder rather than just
   *  longer. Spawn points are room centers (guaranteed open floor), and
   *  any point too close to the player is skipped so a wave can never
   *  materialize on top of them. */
  function spawnWave() {
    if (!holdout) return;
    holdout.wave++;
    const count = WAVE_ENEMY_BASE + Math.floor(holdout.wave / 2);
    const speed = holdout.enemySpeed * (1 + 0.08 * (holdout.wave - 1));
    let placed = 0;
    for (let i = 0; i < count; i++) {
      const sp = holdout.spawnPoints[(holdout.wave + i) % holdout.spawnPoints.length];
      if (Math.hypot(sp.x - posX, sp.y - posY) < 3.5) continue;
      const g = new FpsGuard(sp.x, sp.y, [
        { x: sp.x, y: sp.y },
        { x: posX, y: posY },
      ], speed);
      g.isWaveEnemy = true;
      g.alert = true; // they know exactly where you are — that's the point
      g.sightRange = 20;
      g.sightHalfFov = Math.PI;
      guards.push(g);
      placed++;
    }
    if (placed) window.CG.audio.playWarning();
  }

  /** Rooftop archetype: a barrel detonates when a stun shot connects with
   *  it (see tryFireStun()). The blast permanently defeats every guard in
   *  BARREL_RADIUS — the only thing in FPS Mode that removes an enemy for
   *  good rather than freezing it — and hurts the player too if they're
   *  inside the radius, which is what stops "stand next to a barrel and
   *  shoot it" from being the whole strategy. */
  function detonateBarrel(barrel) {
    if (barrel.exploded) return;
    barrel.exploded = true;
    barrel.flashT = 0.45;
    window.CG.audio.playHit();

    guards.forEach((g) => {
      if (g.defeated) return;
      if (Math.hypot(g.x - barrel.x, g.y - barrel.y) <= BARREL_RADIUS) {
        if (g.isBoss) {
          // The Sentinel isn't one-shot by a barrel — it still takes its
          // normal multi-hit path, so the finale can't be trivialized.
          g.paralyze(STUN_DURATION);
        } else {
          g.defeated = true;
          g.paralyzed = 999;
        }
      }
    });

    // Chain reaction: a barrel in the blast goes up too.
    barrels.forEach((b) => {
      if (!b.exploded && Math.hypot(b.x - barrel.x, b.y - barrel.y) <= BARREL_RADIUS) detonateBarrel(b);
    });

    if (Math.hypot(posX - barrel.x, posY - barrel.y) <= BARREL_RADIUS) {
      playerHealth = Math.max(0, playerHealth - BARREL_PLAYER_DAMAGE);
      hurtFlashTime = 0.5;
      updateHud();
      if (playerHealth <= 0) failMission();
    }
  }

  function updateBarrels(dt) {
    barrels.forEach((b) => { if (b.flashT > 0) b.flashT = Math.max(0, b.flashT - dt); });
  }

  function advanceFloor() {
    if (floorIndex + 1 >= TOTAL_FLOORS) {
      winMission();
      return;
    }
    window.CG.audio.playCheckpoint();
    floorIndex++;
    state = "loading";
    ensureImagesThenBuild(floorIndex, () => { state = "playing"; });
  }

  function failMission() {
    state = "gameover";
    window.FpsModeActive = false;
    if (document.pointerLockElement) document.exitPointerLock();
    window.CG.audio.playGameOver();
    endRun(false, "Too many hits and the alarm trips. Mission over.");
  }

  function winMission() {
    state = "victory";
    window.FpsModeActive = false;
    if (document.pointerLockElement) document.exitPointerLock();
    window.CG.audio.playServerSecured();
    endRun(true, "All 10 floors breached. Every badge accounted for, every elevator cleared.");
  }

  function endRun(won, reasonText) {
    const elapsedSec = Math.max(0, Math.round((performance.now() - startTime) / 1000));
    const name = window.CG.getPlayerName();
    const floorsCleared = won ? TOTAL_FLOORS : floorIndex;
    renderResult({ won, reasonText, name, elapsedSec, floorsCleared });
    UI.showScreen("screen-fps-result");
  }

  function formatTime(totalSec) {
    const m = Math.floor(totalSec / 60).toString().padStart(2, "0");
    const s = (totalSec % 60).toString().padStart(2, "0");
    return `${m}:${s}`;
  }

  function renderResult(data) {
    const set = (id, text) => { const n = document.getElementById(id); if (n) n.textContent = text; };
    const titleEl = document.getElementById("fpsResultTitle");
    const eyebrowEl = document.getElementById("fpsResultEyebrow");
    if (titleEl) titleEl.textContent = data.won ? "TOWER CLEARED" : "SECURITY ALERT";
    if (eyebrowEl) eyebrowEl.textContent = data.won ? "Mission Debrief" : "Mission Failed";
    set("fpsResultPlayerName", data.name);
    set("fpsResultReason", data.reasonText);
    set("fpsResultFloors", `${data.floorsCleared}/${TOTAL_FLOORS}`);
    set("fpsResultBadges", `${badgesCollected}/${badges.length}`);
    set("fpsResultTime", formatTime(data.elapsedSec));

    const card = document.querySelector("#screen-fps-result .card");
    if (card) card.classList.toggle("result-victory", !!data.won);
  }

  /* ---------------- Rendering ---------------- */
  function render() {
    ctx.fillStyle = "#0b1220";
    ctx.fillRect(0, 0, VIEW_W, VIEW_H / 2);

    renderFloorCast();

    for (let col = 0; col < RAY_COLS; col++) {
      const cameraX = (2 * col) / RAY_COLS - 1;
      const rayDirX = dirX + planeX * cameraX;
      const rayDirY = dirY + planeY * cameraX;

      let mapX = Math.floor(posX);
      let mapY = Math.floor(posY);

      const deltaDistX = rayDirX === 0 ? 1e30 : Math.abs(1 / rayDirX);
      const deltaDistY = rayDirY === 0 ? 1e30 : Math.abs(1 / rayDirY);

      let stepX, stepY, sideDistX, sideDistY;
      if (rayDirX < 0) { stepX = -1; sideDistX = (posX - mapX) * deltaDistX; }
      else { stepX = 1; sideDistX = (mapX + 1 - posX) * deltaDistX; }
      if (rayDirY < 0) { stepY = -1; sideDistY = (posY - mapY) * deltaDistY; }
      else { stepY = 1; sideDistY = (mapY + 1 - posY) * deltaDistY; }

      let hit = 0, side = 0, wallType = 1, doorAnim = 0, depth = 0;
      while (hit === 0 && depth < MAX_DEPTH * 2) {
        if (sideDistX < sideDistY) {
          sideDistX += deltaDistX; mapX += stepX; side = 0;
        } else {
          sideDistY += deltaDistY; mapY += stepY; side = 1;
        }
        depth++;
        if (mapX < 0 || mapX >= currentW || mapY < 0 || mapY >= currentH) { hit = 1; wallType = 1; break; }
        const cellVal = currentGrid[mapY][mapX];
        if (cellVal === 0) continue;
        if (cellVal === 3) {
          const anim = doorAnimAt(mapX, mapY);
          if (anim >= 0.92) continue; // fully open — the ray passes straight through
          hit = 1; wallType = 3; doorAnim = anim;
        } else {
          hit = 1; wallType = cellVal;
        }
      }

      const perpWallDist = side === 0
        ? Math.max(0.0001, sideDistX - deltaDistX)
        : Math.max(0.0001, sideDistY - deltaDistY);
      zBuffer[col] = perpWallDist;

      const lineHeight = Math.floor(VIEW_H / perpWallDist);
      const drawStart = Math.max(0, -lineHeight / 2 + VIEW_H / 2);
      const drawEnd = Math.min(VIEW_H, lineHeight / 2 + VIEW_H / 2);

      // Exact wall-hit position, for the texture's horizontal coordinate.
      let wallX = side === 0 ? posY + perpWallDist * rayDirY : posX + perpWallDist * rayDirX;
      wallX -= Math.floor(wallX);
      // A still-locked door (wallType 4, see LOCKED_DOOR) reuses the
      // hazard texture — it should read as "off-limits," not "a door you
      // just haven't opened yet" — until the floor's keycard converts its
      // grid cell to an ordinary door (see the "keycard" pickup handler).
      const texSrc = (wallType === 2 || wallType === 4) ? (side === 0 ? hazardTexLight : hazardTexDark)
        : wallType === 3 ? (side === 0 ? doorTexLight : doorTexDark)
        : (side === 0 ? wallTexLight : wallTexDark);
      const texW = texSrc.width, texH = texSrc.height;
      let texX = Math.floor(wallX * texW);
      if (side === 0 && rayDirX > 0) texX = texW - texX - 1;
      if (side === 1 && rayDirY < 0) texX = texW - texX - 1;
      // A door mid-slide shows a shifted texture window — a cheap but
      // effective "sliding open" read within this column-based renderer.
      if (wallType === 3 && doorAnim > 0) texX = (texX + Math.floor(doorAnim * texW)) % texW;
      texX = Math.max(0, Math.min(texW - 1, texX));

      const fog = Math.min(0.72, perpWallDist / MAX_DEPTH);
      ctx.drawImage(texSrc, texX, 0, 1, texH, col * STRIP_W, drawStart, STRIP_W + 0.5, drawEnd - drawStart);
      if (fog > 0.02) {
        ctx.fillStyle = `rgba(15,23,42,${fog})`;
        ctx.fillRect(col * STRIP_W, drawStart, STRIP_W + 0.5, drawEnd - drawStart);
      }
    }

    drawExitGlow();
    drawSprites();
    if (stunFlashTime > 0) {
      ctx.fillStyle = `rgba(56,189,248,${(stunFlashTime / 0.15) * 0.25})`;
      ctx.fillRect(0, 0, VIEW_W, VIEW_H);
    }
    if (hurtFlashTime > 0) {
      ctx.fillStyle = `rgba(239,68,68,${(hurtFlashTime / 0.35) * 0.35})`;
      ctx.fillRect(0, 0, VIEW_W, VIEW_H);
    }

    drawSniperWarning();
    drawWeaponView();
    drawInteractPrompt();
    drawMouseLookHint();
    drawBossBanner();
    drawHoldoutBanner();
    drawMinimap();
  }

  /** Datacenter archetype: a full-screen warning while a sniper holds a
   *  lock on the player. Drawn in screen space (not as a world sprite)
   *  because the whole point is that it's readable even when the sniper
   *  itself is a distant speck — the player needs to know to get behind a
   *  rack NOW, and how long they have. Escalates as the lock completes. */
  function drawSniperWarning() {
    const locking = snipers.filter((s) => s.hasLock && s.paralyzed <= 0);
    if (!locking.length) return;
    const worst = locking.reduce((a, b) => (a.lockRatio > b.lockRatio ? a : b));
    const r = worst.lockRatio;

    // Red vignette that tightens as the shot charges.
    ctx.save();
    const grad = ctx.createRadialGradient(VIEW_W / 2, VIEW_H / 2, VIEW_H * (0.55 - r * 0.2), VIEW_W / 2, VIEW_H / 2, VIEW_H * 0.95);
    grad.addColorStop(0, "rgba(239,68,68,0)");
    grad.addColorStop(1, `rgba(239,68,68,${0.16 + r * 0.34})`);
    ctx.fillStyle = grad;
    ctx.fillRect(0, 0, VIEW_W, VIEW_H);

    ctx.textAlign = "center";
    ctx.font = "bold 15px 'Share Tech Mono', monospace";
    ctx.fillStyle = "#EF4444";
    ctx.shadowColor = "#EF4444";
    ctx.shadowBlur = 10;
    // Top of the view, not the bottom: the first-person weapon sprite
    // (drawWeaponView) owns the bottom-center third of the screen and
    // was clipping this warning in half — exactly the moment the player
    // most needs to read it. Datacenter floors carry neither the boss
    // banner nor the extraction banner, so this band is free there.
    ctx.fillText("⊕ SNIPER LOCK — BREAK LINE OF SIGHT", VIEW_W / 2, 100);

    // Lock progress bar.
    const barW = 220, barH = 7;
    const barX = VIEW_W / 2 - barW / 2, barY = 110;
    ctx.shadowBlur = 0;
    ctx.fillStyle = "rgba(2,6,23,0.85)";
    ctx.fillRect(barX - 2, barY - 2, barW + 4, barH + 4);
    ctx.fillStyle = "#EF4444";
    ctx.fillRect(barX, barY, barW * r, barH);
    ctx.restore();
  }

  /** Rooftop archetype: the extraction countdown and current wave. */
  function drawHoldoutBanner() {
    if (!holdout) return;
    ctx.save();
    ctx.textAlign = "center";
    if (holdout.complete) {
      ctx.font = "bold 15px 'Share Tech Mono', monospace";
      ctx.fillStyle = "#22C55E";
      ctx.shadowColor = "#22C55E";
      ctx.shadowBlur = 10;
      ctx.fillText("✔ EXTRACTION READY — GET TO THE ELEVATOR", VIEW_W / 2, 52);
    } else {
      const secs = Math.ceil(holdout.timeLeft);
      const urgent = secs <= 10;
      ctx.font = "bold 16px 'Share Tech Mono', monospace";
      ctx.fillStyle = urgent ? "#FACC15" : "#38BDF8";
      ctx.shadowColor = ctx.fillStyle;
      ctx.shadowBlur = 10;
      ctx.fillText(`⏱ EXTRACTION IN ${secs}s  ·  WAVE ${holdout.wave}`, VIEW_W / 2, 52);
      ctx.shadowBlur = 0;
      const barW = 260, barH = 6;
      const barX = VIEW_W / 2 - barW / 2, barY = 60;
      const done = 1 - holdout.timeLeft / holdout.total;
      ctx.fillStyle = "rgba(2,6,23,0.85)";
      ctx.fillRect(barX - 2, barY - 2, barW + 4, barH + 4);
      ctx.fillStyle = urgent ? "#FACC15" : "#38BDF8";
      ctx.fillRect(barX, barY, barW * done, barH);
    }
    ctx.restore();
  }

  /** Classic per-pixel floor-casting (Lodev-style): for each screen row
   *  below the horizon, computes the world-space floor position at both
   *  screen edges and steps across, sampling a tiled/checkerboarded
   *  texture per pixel. Computed at RAY_COLS horizontal resolution and
   *  every other row (then duplicated) to keep this affordable — the
   *  low-res tile pattern reads fine at that density and it keeps this a
   *  cheap per-frame cost rather than a full 900x300 pixel loop. */
  function renderFloorCast() {
    const bufW = RAY_COLS;
    const bufH = VIEW_H / 2;
    const imgData = ctx.createImageData(bufW, bufH);
    const out = imgData.data;
    const rayDirX0 = dirX - planeX, rayDirY0 = dirY - planeY;
    const rayDirX1 = dirX + planeX, rayDirY1 = dirY + planeY;
    const posZ = 0.5 * VIEW_H;

    for (let y = 0; y < bufH; y += FLOOR_ROW_STEP) {
      const p = y + 1; // avoid divide-by-zero right at the horizon
      const rowDistance = posZ / p;
      const floorStepX = (rowDistance * (rayDirX1 - rayDirX0)) / bufW;
      const floorStepY = (rowDistance * (rayDirY1 - rayDirY0)) / bufW;
      let floorX = posX + rowDistance * rayDirX0;
      let floorY = posY + rowDistance * rayDirY0;
      const fog = Math.min(0.75, rowDistance / MAX_DEPTH);
      const fogInv = 1 - fog;

      for (let x = 0; x < bufW; x++) {
        const cellX = Math.floor(floorX), cellY = Math.floor(floorY);
        let tx = Math.floor((floorX - cellX) * FLOOR_TEX_SIZE) & (FLOOR_TEX_SIZE - 1);
        let ty = Math.floor((floorY - cellY) * FLOOR_TEX_SIZE) & (FLOOR_TEX_SIZE - 1);
        const parity = (((cellX % 2) + 2) % 2) ^ (((cellY % 2) + 2) % 2);
        const texData = parity ? floorTexDarkData : floorTexLightData;
        const ti = (ty * FLOOR_TEX_SIZE + tx) * 4;

        const r = texData[ti] * fogInv + 15 * fog;
        const g = texData[ti + 1] * fogInv + 23 * fog;
        const b = texData[ti + 2] * fogInv + 42 * fog;

        const oi = (y * bufW + x) * 4;
        out[oi] = r; out[oi + 1] = g; out[oi + 2] = b; out[oi + 3] = 255;
        if (FLOOR_ROW_STEP > 1 && y + 1 < bufH) {
          const oi2 = ((y + 1) * bufW + x) * 4;
          out[oi2] = r; out[oi2 + 1] = g; out[oi2 + 2] = b; out[oi2 + 3] = 255;
        }

        floorX += floorStepX;
        floorY += floorStepY;
      }
    }

    // Blit the low-res floor buffer up to full canvas resolution, blocky
    // (no smoothing) to match the flat-shaded/chunky aesthetic.
    const off = renderFloorCast._off || (renderFloorCast._off = document.createElement("canvas"));
    off.width = bufW; off.height = bufH;
    off.getContext("2d").putImageData(imgData, 0, 0);
    ctx.imageSmoothingEnabled = false;
    ctx.drawImage(off, 0, 0, bufW, bufH, 0, VIEW_H / 2, VIEW_W, VIEW_H / 2);
  }

  function drawExitGlow() {
    const [ec, er] = currentExitCells[0];
    const dx = ec + 0.5 - posX, dy = er + 0.5 - posY;
    const dist = Math.hypot(dx, dy);
    if (dist > 10) return;
    const alpha = Math.max(0, 0.35 - dist * 0.03);
    const lit = badgesCollected >= badges.length && (!currentBoss || currentBoss.defeated);
    ctx.fillStyle = lit ? `rgba(34,197,94,${alpha})` : `rgba(148,163,184,${alpha * 0.6})`;
    ctx.fillRect(0, VIEW_H * 0.35, VIEW_W, VIEW_H * 0.15);
  }

  /** A persistent readout for Floor 10's Sentinel fight, once it's awake —
   *  mirrors Story Mode's boss HUD (a name + hit counter) so the same
   *  "how much longer" feedback exists here too. */
  function drawBossBanner() {
    if (!currentBoss || !currentBoss.awake) return;
    ctx.save();
    ctx.textAlign = "center";
    ctx.font = "bold 15px 'Share Tech Mono', monospace";
    if (currentBoss.defeated) {
      ctx.fillStyle = "#22C55E";
      ctx.shadowColor = "#22C55E";
      ctx.shadowBlur = 8;
      ctx.fillText(`${currentBoss.name.toUpperCase()} IS DOWN — the elevator is clear`, VIEW_W / 2, 52);
    } else {
      ctx.fillStyle = "#EF4444";
      ctx.shadowColor = "#EF4444";
      ctx.shadowBlur = 8;
      ctx.fillText(`⚠ ${currentBoss.name.toUpperCase()} — HITS ${currentBoss.hitsTaken}/${currentBoss.maxHits}`, VIEW_W / 2, 52);
    }
    ctx.restore();
  }

  // Billboard sprites (badges + guards + the hacking terminal) via the
  // inverse camera matrix, sorted back-to-front, occluded by the wall
  // zBuffer.
  function drawSprites() {
    const sprites = [];
    badges.forEach((b) => { if (!b.collected) sprites.push({ x: b.x, y: b.y, type: "badge" }); });
    guards.forEach((g) => sprites.push({ x: g.x, y: g.y, type: "guard", g }));
    barrels.forEach((b) => { if (!b.exploded || b.flashT > 0) sprites.push({ x: b.x, y: b.y, type: "barrel", b }); });
    if (currentTerminal) sprites.push({ x: currentTerminal.x, y: currentTerminal.y, type: "terminal" });
    pickups.forEach((pk) => { if (!pk.collected) sprites.push({ x: pk.x, y: pk.y, type: "pickup", pk }); });

    sprites.sort((a, b) => {
      const da = (a.x - posX) ** 2 + (a.y - posY) ** 2;
      const db = (b.x - posX) ** 2 + (b.y - posY) ** 2;
      return db - da;
    });

    const invDet = 1 / (planeX * dirY - dirX * planeY);
    const trophyImg = window.SPRITES && window.SPRITES.platformTiles;
    const guardImg = window.SPRITES && window.SPRITES.daveGuard;
    const sentinelImg = window.SPRITES && window.SPRITES.sentinelGuard;

    sprites.forEach((sp) => {
      const spriteX = sp.x - posX;
      const spriteY = sp.y - posY;
      const transformX = invDet * (dirY * spriteX - dirX * spriteY);
      const transformY = invDet * (-planeY * spriteX + planeX * spriteY);
      if (transformY <= 0.15) return;

      const screenX = Math.floor((VIEW_W / 2) * (1 + transformX / transformY));
      const spriteSize = sp.type === "guard" ? (sp.g.isBoss ? 1.3 : 0.9)
        : sp.type === "terminal" ? 0.7
        : sp.type === "pickup" ? 0.36
        : sp.type === "barrel" ? (sp.b.flashT > 0 ? 1.6 : 0.62)
        : 0.42;
      const spriteHeight = Math.abs(Math.floor((VIEW_H / transformY) * spriteSize));
      const spriteWidth = sp.type === "terminal" ? spriteHeight * (160 / 224) : spriteHeight;

      const drawStartY = Math.floor(-spriteHeight / 2 + VIEW_H / 2 + (sp.type === "guard" ? VIEW_H * 0.06 : sp.type === "terminal" ? VIEW_H * 0.02 : 0));
      const drawStartX = Math.floor(screenX - spriteWidth / 2);

      const col0 = Math.max(0, Math.floor(drawStartX / STRIP_W));
      const col1 = Math.min(RAY_COLS - 1, Math.floor((drawStartX + spriteWidth) / STRIP_W));
      let anyVisible = false;
      for (let c = col0; c <= col1; c++) {
        if (transformY < zBuffer[c]) { anyVisible = true; break; }
      }
      if (!anyVisible) return;

      ctx.save();
      const region = new Path2D();
      for (let c = col0; c <= col1; c++) {
        if (transformY < zBuffer[c]) {
          region.rect(c * STRIP_W, 0, STRIP_W + 0.5, VIEW_H);
        }
      }
      ctx.clip(region);
      ctx.imageSmoothingEnabled = false;

      if (sp.type === "badge" && trophyImg && trophyImg.complete && trophyImg.naturalWidth > 0) {
        ctx.drawImage(
          trophyImg, TROPHY_SRC.x, TROPHY_SRC.y, TROPHY_SRC.w, TROPHY_SRC.h,
          drawStartX, drawStartY, spriteWidth, spriteHeight
        );
      } else if (sp.type === "badge") {
        ctx.fillStyle = "#FACC15";
        ctx.beginPath();
        ctx.arc(screenX, drawStartY + spriteHeight / 2, spriteWidth / 2.4, 0, Math.PI * 2);
        ctx.fill();
      } else if (sp.type === "terminal" && IMG_TERMINAL.complete && IMG_TERMINAL.naturalWidth > 0) {
        if (currentTerminal && currentTerminal.hacked) ctx.filter = "hue-rotate(60deg) saturate(1.3)";
        ctx.drawImage(IMG_TERMINAL, drawStartX, drawStartY, spriteWidth, spriteHeight);
        ctx.filter = "none";
      } else if (sp.type === "guard" && sp.g.isBoss && sentinelImg && sentinelImg.complete && sentinelImg.naturalWidth > 0) {
        // The Sentinel gets its own dedicated sprite (see
        // tools/gen_villain_boss_sprite.py) instead of the ordinary
        // guard art with a color filter, same "the boss looks like a
        // distinct character" treatment as Story Mode's Boss.draw().
        const frameW = sentinelImg.naturalWidth / 2;
        const frameH = sentinelImg.naturalHeight;
        const frame = Math.floor(sp.g.animPhase) % 2;
        if (sp.g.defeated) ctx.filter = "grayscale(1) brightness(0.6)";
        else if (sp.g.paralyzed > 0) ctx.filter = "grayscale(1) brightness(0.75)";
        ctx.drawImage(
          sentinelImg, frame * frameW, 0, frameW, frameH,
          drawStartX, drawStartY, spriteWidth, spriteHeight
        );
        ctx.filter = "none";
      } else if (sp.type === "guard" && guardImg && guardImg.complete && guardImg.naturalWidth > 0) {
        const frameW = guardImg.naturalWidth / 2;
        const frameH = guardImg.naturalHeight;
        const frame = Math.floor(sp.g.animPhase) % 2;
        if (sp.g.defeated) ctx.filter = "grayscale(1) brightness(0.6)";
        else if (sp.g.paralyzed > 0) ctx.filter = "grayscale(1) brightness(0.75)";
        else if (sp.g.isBoss) ctx.filter = "hue-rotate(320deg) saturate(1.6) brightness(1.05)";
        ctx.drawImage(
          guardImg, frame * frameW, 0, frameW, frameH,
          drawStartX, drawStartY, spriteWidth, spriteHeight
        );
        ctx.filter = "none";
      } else if (sp.type === "barrel") {
        // A live barrel reads as a hazard-striped drum; a detonating one
        // is a brief expanding orange flash at the same world position.
        const bx = screenX;
        const byTop = drawStartY;
        if (sp.b.flashT > 0) {
          const f = sp.b.flashT / 0.45;
          ctx.globalAlpha = f;
          const grad = ctx.createRadialGradient(bx, byTop + spriteHeight / 2, 0, bx, byTop + spriteHeight / 2, spriteWidth / 2);
          grad.addColorStop(0, "#FEF3C7");
          grad.addColorStop(0.45, "#F97316");
          grad.addColorStop(1, "rgba(239,68,68,0)");
          ctx.fillStyle = grad;
          ctx.beginPath();
          ctx.arc(bx, byTop + spriteHeight / 2, spriteWidth / 2, 0, Math.PI * 2);
          ctx.fill();
          ctx.globalAlpha = 1;
        } else {
          const bw = spriteWidth * 0.62;
          ctx.fillStyle = "#B45309";
          ctx.strokeStyle = "#FBBF24";
          ctx.lineWidth = Math.max(1, spriteWidth * 0.05);
          ctx.fillRect(bx - bw / 2, byTop, bw, spriteHeight);
          ctx.strokeRect(bx - bw / 2, byTop, bw, spriteHeight);
          // Two hazard bands so it's unmistakably an explosive drum.
          ctx.fillStyle = "#FBBF24";
          [0.28, 0.62].forEach((t) => ctx.fillRect(bx - bw / 2, byTop + spriteHeight * t, bw, spriteHeight * 0.1));
        }
      } else if (sp.type === "pickup") {
        const color = sp.pk.type === "keycard" ? "#F59E0B" : sp.pk.type === "health" ? "#22C55E" : "#38BDF8";
        const icon = sp.pk.type === "keycard" ? "🔑" : sp.pk.type === "health" ? "✚" : "⚡";
        ctx.fillStyle = "#0F172A";
        ctx.strokeStyle = color;
        ctx.lineWidth = 2;
        ctx.shadowColor = color;
        ctx.shadowBlur = 8;
        ctx.beginPath();
        ctx.arc(screenX, drawStartY + spriteHeight / 2, spriteWidth / 2.2, 0, Math.PI * 2);
        ctx.fill();
        ctx.stroke();
        ctx.shadowBlur = 0;
        ctx.fillStyle = color;
        ctx.font = `bold ${Math.round(spriteHeight * 0.5)}px 'Share Tech Mono', monospace`;
        ctx.textAlign = "center";
        ctx.textBaseline = "middle";
        ctx.fillText(icon, screenX, drawStartY + spriteHeight / 2 + 1);
      } else {
        ctx.fillStyle = sp.g && sp.g.paralyzed > 0 ? "#64748B" : "#EF4444";
        ctx.fillRect(drawStartX, drawStartY, spriteWidth, spriteHeight);
      }
      ctx.restore();
    });
  }

  // Wolfenstein-3D-style first-person weapon view: the stun pistol,
  // anchored bottom-center, a light idle bob while walking, and a
  // muzzle-flash frame swap for a beat after firing.
  function drawWeaponView() {
    if (!IMG_GUN_HAND.complete || IMG_GUN_HAND.naturalWidth === 0) return;
    const scale = 1.55;
    const w = GUN_FRAME_W * scale * (VIEW_W / 1600);
    const h = GUN_FRAME_H * scale * (VIEW_W / 1600);
    const bob = Math.sin(bobPhase) * 8;
    const bobX = Math.cos(bobPhase * 0.5) * 6;
    const x = VIEW_W / 2 - w / 2 + bobX;
    const y = VIEW_H - h + 30 + Math.abs(bob);
    const frame = gunFireTime > 0 ? 1 : 0;
    ctx.imageSmoothingEnabled = false;
    ctx.drawImage(IMG_GUN_HAND, frame * GUN_FRAME_W, 0, GUN_FRAME_W, GUN_FRAME_H, x, y, w, h);
  }

  /** A "Press E to hack" prompt when standing near the Floor 1 terminal
   *  and it hasn't been solved yet. */
  function drawInteractPrompt() {
    if (!currentTerminal || currentTerminal.hacked) return;
    const dist = Math.hypot(currentTerminal.x - posX, currentTerminal.y - posY);
    if (dist > INTERACT_RADIUS) return;
    ctx.save();
    ctx.font = "bold 15px 'Share Tech Mono', monospace";
    ctx.textAlign = "center";
    ctx.fillStyle = "#22C55E";
    ctx.shadowColor = "#22C55E";
    ctx.shadowBlur = 8;
    ctx.fillText("Press E (or the ⌨ button) to hack the terminal", VIEW_W / 2, VIEW_H - 110);
    ctx.restore();
  }

  /** A dismissible-feeling banner (it's just informational, no click
   *  needed to clear it — it disappears the moment the pointer locks)
   *  reminding the player mouse-look is available. */
  function drawMouseLookHint() {
    if (pointerLocked) return;
    ctx.save();
    ctx.fillStyle = "rgba(2,6,23,0.55)";
    ctx.fillRect(0, 0, VIEW_W, 30);
    ctx.font = "12px 'Share Tech Mono', monospace";
    ctx.fillStyle = "#94A3B8";
    ctx.textAlign = "center";
    ctx.fillText("🖱 Click the view to steer with the mouse (keyboard still walks) — Esc to release", VIEW_W / 2, 19);
    ctx.restore();
  }

  function drawMinimap() {
    const w = mmCanvas.width, h = mmCanvas.height;
    mmCtx.clearRect(0, 0, w, h);
    const scale = Math.min(w / currentW, h / currentH);
    mmCtx.fillStyle = "rgba(2,6,23,0.4)";
    mmCtx.fillRect(0, 0, w, h);
    for (let r = 0; r < currentH; r++) {
      for (let c = 0; c < currentW; c++) {
        const val = currentGrid[r][c];
        if (val === 0) continue;
        if (val === 3) {
          const anim = doorAnimAt(c, r);
          mmCtx.fillStyle = anim >= 0.92 ? "rgba(161,98,7,0.35)" : "#A16207";
        } else if (val === LOCKED_DOOR) {
          mmCtx.fillStyle = "#DC2626"; // still-locked door — reads as a hazard, not a normal one
        } else {
          mmCtx.fillStyle = val === 2 ? "#F59E0B" : currentTint;
        }
        mmCtx.fillRect(c * scale, r * scale, scale, scale);
      }
    }
    badges.forEach((b) => {
      if (b.collected) return;
      mmCtx.fillStyle = "#FACC15";
      mmCtx.beginPath();
      mmCtx.arc(b.x * scale, b.y * scale, Math.max(1.5, scale * 0.25), 0, Math.PI * 2);
      mmCtx.fill();
    });
    if (currentTerminal && !currentTerminal.hacked) {
      mmCtx.fillStyle = "#22C55E";
      mmCtx.fillRect(currentTerminal.x * scale - 2, currentTerminal.y * scale - 2, 4, 4);
    }
    pickups.forEach((pk) => {
      if (pk.collected) return;
      mmCtx.fillStyle = pk.type === "keycard" ? "#F59E0B" : pk.type === "health" ? "#22C55E" : "#38BDF8";
      mmCtx.beginPath();
      mmCtx.arc(pk.x * scale, pk.y * scale, Math.max(1.5, scale * 0.22), 0, Math.PI * 2);
      mmCtx.fill();
    });
    guards.forEach((g) => {
      mmCtx.fillStyle = g.paralyzed > 0 ? "#64748B" : "#EF4444";
      mmCtx.beginPath();
      mmCtx.arc(g.x * scale, g.y * scale, Math.max(1.5, scale * 0.3), 0, Math.PI * 2);
      mmCtx.fill();
    });

    mmCtx.save();
    mmCtx.translate(posX * scale, posY * scale);
    mmCtx.rotate(angle);
    mmCtx.fillStyle = "#22C55E";
    mmCtx.beginPath();
    mmCtx.moveTo(6, 0);
    mmCtx.lineTo(-4, 4);
    mmCtx.lineTo(-4, -4);
    mmCtx.closePath();
    mmCtx.fill();
    mmCtx.restore();
  }

  /* ---------------- QA hooks ---------------- */
  function debugPos() {
    return {
      state, x: posX, y: posY, angle,
      floorIndex, totalFloors: TOTAL_FLOORS, floorName: currentFloorName,
      badgesCollected, badgesTotal: badges.length,
      stunCharges,
      guards: guards.map((g) => ({
        x: g.x, y: g.y, paralyzed: g.paralyzed, facingAngle: g.facingAngle,
        isBoss: !!g.isBoss, hitsTaken: g.hitsTaken, maxHits: g.maxHits, defeated: !!g.defeated,
      })),
      pointerLocked,
      doorCount: doorStates.size,
      // Grid dimensions + every entity's live position, so a test can run
      // its own flood-fill over __debugGridValueAt() and assert the floor
      // is genuinely completable — the same verify-before-wire
      // connectivity check this mode's layouts have always been held to,
      // now runnable against the live grid rather than a separate script.
      gridW: currentW,
      gridH: currentH,
      badgesInfo: badges.map((b) => ({ x: b.x, y: b.y, collected: b.collected })),
      pickupsInfo: pickups.map((pk) => ({ x: pk.x, y: pk.y, type: pk.type, collected: pk.collected })),
      // ---- Level archetype (see archetypeFor()) ----
      archetype: currentArchetype,
      archetypeLabel: ARCHETYPE_LABEL[currentArchetype],
      snipers: snipers.map((s) => ({
        x: s.x, y: s.y, hasLock: s.hasLock, lockRatio: s.lockRatio,
        lockT: s.lockT, cooldownT: s.cooldownT, paralyzed: s.paralyzed,
      })),
      barrels: barrels.map((b) => ({ x: b.x, y: b.y, exploded: b.exploded })),
      holdout: holdout ? {
        total: holdout.total, timeLeft: holdout.timeLeft,
        wave: holdout.wave, complete: holdout.complete,
      } : null,
      waveEnemies: guards.filter((g) => g.isWaveEnemy && !g.defeated).length,
      terminal: currentTerminal ? { x: currentTerminal.x, y: currentTerminal.y, hacked: currentTerminal.hacked } : null,
      exitCells: currentExitCells,
      playerHealth,
      hasKeycard,
      lockedDoorCell: currentLockedDoorCell,
      pickups: pickups.map((p) => ({ x: p.x, y: p.y, type: p.type, collected: p.collected })),
      boss: currentBoss ? {
        awake: currentBoss.awake, defeated: currentBoss.defeated,
        hitsTaken: currentBoss.hitsTaken, maxHits: currentBoss.maxHits,
      } : null,
    };
  }

  function __debugTeleport(x, y) {
    posX = x; posY = y;
  }

  function __debugCollectAllBadges() {
    badges.forEach((b) => { b.collected = true; });
    badgesCollected = badges.length;
    updateHud();
  }

  function __debugParalyzeGuard(index, duration) {
    const g = guards[index || 0];
    if (g) g.paralyze(duration != null ? duration : 999);
  }

  function __debugSkipToFloor(idx) {
    floorIndex = Math.max(0, Math.min(TOTAL_FLOORS - 1, idx));
    state = "loading";
    ensureImagesThenBuild(floorIndex, () => { state = "playing"; });
  }

  /** QA helper: forces the mouse-look input branch (strafe-vs-turn) on
   *  without needing a real OS-level Pointer Lock grant, which headless
   *  test runners can't reliably obtain. No normal gameplay path calls
   *  this — real mouse-look is driven by the actual pointerlockchange
   *  event above. */
  function __debugSetPointerLocked(v) {
    pointerLocked = !!v;
  }

  /** QA helper: rotates the view directly, bypassing both the keyboard
   *  turn path and the real mousemove listener, so a test can exercise
   *  "mouse-look moved the camera" without a real Pointer Lock grant. */
  function __debugRotate(deltaRadians) {
    angle += deltaRadians;
    if (angle > Math.PI) angle -= Math.PI * 2;
    if (angle < -Math.PI) angle += Math.PI * 2;
    updateDirPlane();
  }

  /** QA helper: exercises the exact same code path pressing E does, for
   *  tests that can't easily dispatch a real keydown at the right moment. */
  function __debugInteract() {
    tryInteract();
  }

  /** QA helper: answers the terminal puzzle correctly regardless of what's
   *  currently open, short-circuiting straight to "hacked" so a test can
   *  verify the reward without clicking through the real mini-puzzle UI. */
  function __debugForceHackTerminal() {
    if (!currentTerminal || currentTerminal.hacked) return;
    currentTerminal.hacked = true;
    stunCharges = Math.min(STUN_CHARGES_CAP, stunCharges + 1);
    updateHud();
  }

  /** QA helper: force-opens every door on the current floor — including
   *  converting any still-locked keycard door to an ordinary open one —
   *  useful for tests that want to verify full-floor reachability without
   *  waiting on the proximity-based auto-open animation or picking up the
   *  keycard first. */
  function __debugOpenAllDoors() {
    for (let r = 0; r < currentH; r++) {
      for (let c = 0; c < currentW; c++) {
        if (currentGrid[r][c] === LOCKED_DOOR) currentGrid[r][c] = 3;
      }
    }
    doorStates.forEach((d) => { d.open = true; d.anim = 1; d.closeTimer = DOOR_AUTO_CLOSE_DELAY; });
  }

  /** QA helper: calls a guard's own canDetect() directly against an
   *  arbitrary point, for deterministically testing the forward-facing-
   *  cone detection logic without racing the guard's own per-frame
   *  movement/facing updates. No normal gameplay path calls this. */
  function __debugCanGuardDetect(index, x, y) {
    const g = guards[index || 0];
    if (!g) return null;
    return g.canDetect(x, y);
  }

  /** QA helper: reads a raw grid cell value at (col, row) — e.g. to
   *  confirm a locked door cell (LOCKED_DOOR, 4) actually converts to an
   *  ordinary door (3) once the keycard is collected. No normal gameplay
   *  path calls this. */
  function __debugGridValueAt(c, r) {
    if (r < 0 || r >= currentH || c < 0 || c >= currentW) return null;
    return currentGrid[r][c];
  }

  /** QA helper: directly sets player health (clamped to [0, MAX]), for
   *  exercising the damage/death path without needing a real guard to
   *  land HURT_INVULN-gated hits over several frames. No normal gameplay
   *  path calls this. */
  function __debugSetHealth(v) {
    playerHealth = Math.max(0, Math.min(PLAYER_MAX_HEALTH, v));
    updateHud();
  }

  /** QA helper: grants this floor's keycard directly (and unlocks its
   *  door, same as the real pickup does), bypassing the need to physically
   *  find and walk over it. No normal gameplay path calls this. */
  function __debugGiveKeycard() {
    hasKeycard = true;
    if (currentLockedDoorCell) {
      const [lc, lr] = currentLockedDoorCell;
      currentGrid[lr][lc] = 3;
    }
    updateHud();
  }

  /** QA helper: wakes the final floor's Sentinel directly (same as
   *  collecting every badge would) without needing a test to actually
   *  gather all of them first. No-ops on every floor but the last. No
   *  normal gameplay path calls this. */
  function __debugWakeBoss() {
    if (!currentBoss || currentBoss.awake) return;
    currentBoss.awake = true;
    guards.push(currentBoss);
  }

  /** QA helper: drives the final floor's Sentinel straight to "defeated" —
   *  wakes it first (see __debugWakeBoss()) if needed, then repeatedly
   *  calls its own paralyze() (the same method a real stun hit calls)
   *  until it reports defeated. No normal gameplay path calls this. */
  function __debugForceDefeatFpsBoss() {
    if (!currentBoss) return;
    __debugWakeBoss();
    let guardRail = 0;
    while (!currentBoss.defeated && guardRail < 10) { currentBoss.paralyze(0.01); guardRail++; }
  }

  /* ---------------- QA hooks: level archetypes ---------------- */

  /** Teleports the player into a sniper's clear line of sight (one grid
   *  unit toward the arena from the sniper) so a test can watch a real
   *  lock build through updateSniper() rather than forcing its state. */
  function __debugTeleportIntoSniperView(index) {
    const s = snipers[index || 0];
    if (!s) return false;
    // Scan outward in every direction (not just the sniper's current
    // facing — it's omnidirectional, and its facing only reflects the
    // last thing it locked) for an open cell with genuine line of sight.
    for (let d = 2; d <= 9; d += 0.5) {
      for (let a = 0; a < Math.PI * 2; a += Math.PI / 8) {
        const tx = s.x + Math.cos(a) * d;
        const ty = s.y + Math.sin(a) * d;
        if (isWall(tx, ty)) continue;
        if (s.hasLineOfSight(tx, ty)) { posX = tx; posY = ty; return true; }
      }
    }
    return false;
  }

  /** Advances a sniper's lock to just under firing, so the next real
   *  update() tick fires it — exercises the actual damage path. */
  function __debugPrimeSniper(index) {
    const s = snipers[index || 0];
    if (!s) return false;
    s.cooldownT = 0;
    s.lockT = SNIPER_LOCK_TIME - 0.02;
    return true;
  }

  /** Fast-forwards the rooftop extraction timer to `secondsLeft`, so a
   *  test doesn't have to sit through a 45+ second hold-out in real time. */
  function __debugSetHoldout(secondsLeft) {
    if (!holdout) return false;
    holdout.timeLeft = Math.max(0, secondsLeft);
    if (holdout.timeLeft <= 0) holdout.complete = true;
    return true;
  }

  /** Triggers one wave immediately through the real spawnWave() path. */
  function __debugSpawnWave() {
    if (!holdout) return null;
    spawnWave();
    return { wave: holdout.wave, waveEnemies: guards.filter((g) => g.isWaveEnemy && !g.defeated).length };
  }

  /** Teleports next to a barrel then detonates it through the real
   *  tryFireStun() targeting path, so the test covers aiming at a barrel
   *  rather than just calling detonateBarrel() directly. */
  function __debugShootBarrel(index) {
    const b = barrels[index || 0];
    if (!b || b.exploded) return null;
    // Stand back far enough to survive the blast, facing the barrel.
    const dist = BARREL_RADIUS + 1.2;
    for (const dir of [0, Math.PI / 2, Math.PI, -Math.PI / 2]) {
      const tx = b.x + Math.cos(dir) * dist;
      const ty = b.y + Math.sin(dir) * dist;
      if (isWall(tx, ty)) continue;
      posX = tx; posY = ty;
      angle = Math.atan2(b.y - posY, b.x - posX);
      updateDirPlane();
      stunCharges = Math.max(stunCharges, 1);
      tryFireStun();
      return { exploded: b.exploded, playerHealth };
    }
    return null;
  }

  return {
    start, restart, debugPos,
    __debugTeleport, __debugCollectAllBadges, __debugParalyzeGuard, __debugSkipToFloor,
    __debugSetPointerLocked, __debugRotate, __debugInteract, __debugForceHackTerminal, __debugOpenAllDoors,
    __debugCanGuardDetect, __debugSetHealth, __debugGiveKeycard, __debugWakeBoss, __debugForceDefeatFpsBoss,
    __debugGridValueAt,
    __debugTeleportIntoSniperView, __debugPrimeSniper, __debugSetHoldout, __debugSpawnWave, __debugShootBarrel,
    // Exposes the live wall test so a suite can pick probe points that
    // are genuinely in open floor rather than assuming a room size.
    __debugIsWall: (x, y) => isWall(x, y),
  };
})();
